### ISSUE TITLE
[EPIC] Activity UI

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#10025]
Discussion: https://www.notion.so/New-Activity-View-34b9d4af750e468a91858a86675ace81
Design: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=11019-134543
Architecture:

![WalletActivityPart](https://user-images.githubusercontent.com/491074/230379511-1ac3f36c-6e3e-4ebb-a565-3ef589e800be.jpeg)

## Related Issues:
- [x] [Wallet: Activity tab not loading 20 items at a time#9814](https://github.com/status-im/status-desktop/issues/9814)
- [x] [Refresh Transactions CurrencyAmount instances when format changes](https://github.com/status-im/status-desktop/issues/9548)
- [x] [Wallet: transaction hash must be present in activity (transaction details)#9022](https://github.com/status-im/status-desktop/issues/9022)
- [x] [Loading more transactions in Activity View resets the Listview #9617](https://github.com/status-im/status-desktop/issues/9617)
- [x] [Dummy loading items are clickable](https://github.com/status-im/status-desktop/issues/10083)
- [x] [Delay after clicking the Activity tab before the skeleton loading starts](https://github.com/status-im/status-desktop/issues/10232)
- [x] [Ensure transaction items are loaded sequentially on Activities list view](https://github.com/status-im/status-desktop/issues/10233)
- [ ] [Query contact public key using wallet address](https://github.com/status-im/status-desktop/issues/10760)
- [x] #11333
- [x] #11377 
- [x] #11412
- [x] #11447
- [x] https://github.com/status-im/status-desktop/issues/11717
- [x] https://github.com/status-im/status-desktop/issues/11754
- [x] Finalized status is never used

## QML Components
- [x] Account List with combined view
- [x] New Header https://github.com/status-im/status-desktop/issues/10330
- [x] New Network selector https://github.com/status-im/status-desktop/issues/10330
- [x] #10333
- [x] #10443
- [x] #10432
- [x] #10473
- [x] #10542
- [x] #10639
- [x] #10583
- [x] #10619
- [x] #10751
- [x] #10786
- [x] #10787
- [x] #10792
- [ ] Activity Details Bridge Link
- [x] #10776
- [x] #10822
- [x] #10823
- [x] #10796
 
## New features For activity
- [x] #10366
- [x] #11017
- [x] #10251
- [x] #10790
- [ ] #10791
- [x] #10762
- [x] #10848
- [x] Copy tx
- [x] #12122
- [x] #12123
- [ ] #12093 - (Contract Deployment and Minting activity filtering
- [x] #10246
- [x] #10474
- [x] #11139
- [x] #11080
- [ ] #12120

## Combine View
- [x] #10247

## Extra
- [x] #11233
- [ ] #11171 - content-dependent filtering criteria: NFTs, Tokens (we show the list from assets)
- [x] #9047
- [x] Unknown token details view; details https://github.com/status-im/status-desktop/issues/11043
- [ ] Known counterparty (CEX) address detection https://github.com/status-im/status-desktop/issues/10956
- [x] #11566
- [ ] Filter and show destroy event (community-related)
- [ ] #11414
- [x] https://github.com/status-im/status-desktop/issues/11534
- [x] #11564

## Optimizations

- [x] #11631
- [x] #11173
  - [x] #11597
  - [x] #11598
- [x] #11351
- [x] #11018
- [x] #11036
- [x] #12077
- [ ] Extend recipients model with name and ens

## Cleanup
- [x] #11380
