### ISSUE TITLE
[EPIC] Indicate notifications on Status App icon on the taskbar

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#10466]
## Problem
When a user has unread messages or mentions, if they missed a notification they have no idea unless they open the app.

## Desired Behaviour
Display a badge on the application icon to indicate there is unread messages or mentions.

**Use case: unread messages**

Precondition: User has application minimized
1. User receives 5 new messages
2. Application Icon displays a badge with the number 5

**Use case: unread mentions**

Precondition: User has application minimized
1. User receives a mention
2. Application Icon displays a badge with the symbol `@`

### Previous work & Challenges

This had 2 long standing issues, but it seems like not working in MacOS either. Needs an overall solution.

### Epic Issues

First step with just a red dot:
- [x] https://github.com/status-im/status-desktop/issues/14788
- [x] https://github.com/status-im/status-desktop/issues/14789 (previously [5332](https://github.com/status-im/status-desktop/issues/5332))
- [x] https://github.com/status-im/status-desktop/issues/14790 (previously [5333](https://github.com/status-im/status-desktop/issues/5333))

Final step with number marker (for later):
- [ ] Indicate notifications on Status App icon on the taskbar on MacOS
- [ ] Indicate notifications on Status App icon on the taskbar on Windows (previously [5332](https://github.com/status-im/status-desktop/issues/5332))
- [ ] Indicate notifications on Status App icon on the taskbar on Linux (previously [5333](https://github.com/status-im/status-desktop/issues/5333))

**Comment by iurimatias** [comment]
@John-44 @benjthayer Can you confirm this is the desired behaviour? it's not clear for instance if receiving a message should override the badge to display `@` instead of the number of messages

**Comment by caybro** [comment]
This could be a very small "fix", e.g. what Discord does, it draws a small red dot in the bottom right corner over the app icon in system tray

**Comment by caybro** [comment]
The concept of a minimized application here is kinda blurred, e.g. on Linux, the icon/task switcher is hidden by default, on Windows you can set it up to auto hide too...

**Comment by benjthayer** [comment]
> @John-44 @benjthayer Can you confirm this is the desired behaviour? it's not clear for instance if receiving a message should override the badge to display `@` instead of the number of messages

Certainly a nice enhancement to explore. We would need to consider not just unread mentions however but all notifications across the app - eg an received transaction, dApp sign requests, contact requests etc. and how that works across different operating systems - not a quick one and one we would want to spend some time going through but definitely valid!

@John-44 can perhaps guid more on prioritisation and timings
