### ISSUE TITLE
[EPIC] [Community Permission] Channel based permissions

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10598]
Big lines of the feature:
- Create, edit and delete channel token permissions in the permissions admin screens
- All user facing channel token permissions functionality e.g. what happens when a user tries to access a token gated channel they don't have the required tokens to access, what happens when a user only has permissions to view a channel, etc...
- If a community is an open (not token gated at the community level) community, if a channel is token gated, then the channel should be automatically encrypted. If token gating is removed from a channel, the channel should become unencrypted.

Issues will be attached to this Epic to track them.

I recommend starting with a normal "read and write" channel and then we can do a "read only channel".

The harder part is making sure encryption works well on the backend per channel. So a good starting issue would be to create the backend to handle the keys/encryption for specific users for specific channels. It,s possible to use the same `groupID` for all the channels in the permission, but it might be simpler to have a different `groupID` per channel 

Contact @Samyoul before starting work on this to get tips and also see where he is at, because he was improving the key propagation mechanism.

Design: [Permissions](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=2934-478959&t=8nkvY8DpjdyRPXsM-0)

Tasks:

- [x] https://github.com/status-im/status-desktop/issues/10993
- [x] https://github.com/status-im/status-desktop/issues/10995
- [x] https://github.com/status-im/status-desktop/issues/10996
- [x] https://github.com/status-im/status-desktop/issues/10997

For 0.14:

- [x] https://github.com/status-im/status-desktop/issues/10998
- [x] #11660

**Comment by 0x-r4bbit** [comment]
> This includes the "no tokens required to view this channel" permission

^ This essentially means, no channel permission for this channel, or am I missing something here?

**Comment by jrainville** [comment]
> > This includes the "no tokens required to view this channel" permission
> 
> ^ This essentially means, no channel permission for this channel, or am I missing something here?

I don't remember what I meant and I can't find anywhere in the design where we have that, so I removed the line. Sorry for the confusion.

I think it might have been about read-only channels for all users? Anyway, I think we need a better mechanism for read-only channels than token permissions, especially for all users
