### ISSUE TITLE
[EPIC] [Community Settings] Base view classes refactor / files reorganization and cleanups

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11136]
### Description
This is an EPIC task to list all subtasks needed to sanitize `Community Settings` qml views / flows. Also to reorganize and cleanup repository.

The subtasks can be done isolated but the preferable order is the one listed below:

- [x] https://github.com/status-im/status-desktop/issues/6204

- [x] https://github.com/status-im/status-desktop/issues/11265

- [x] https://github.com/status-im/status-desktop/issues/11050

- [x] https://github.com/status-im/status-desktop/issues/11177

- [x] https://github.com/status-im/status-desktop/issues/11179

- [x] https://github.com/status-im/status-desktop/issues/11180
