### ISSUE TITLE
[EPIC] New Settings

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#11130]
Design: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=2499-150211&t=9KNNvAQQjs6WwKuC-0

## Wallet accounts
- [x] #11237
- [x] #11189
- [x] #11221

## Networks
- [x] #11252
- [x] #11434
- [x] Networks - Revert Network to default
- [x] #11465

## Account Order
- [x] #11133
- [x] #11263

## Account Interaction
- [x] #10769
- [x] #11707
- [ ] #11737

## Account view
- [x] #11537
- [x] #11578
- [x] #11689
- [x] Account view - Remove account - already done - https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=15479%3A316286&mode=dev
- [x] https://github.com/status-im/status-desktop/issues/11493

## Syncing
- [x] #11779
- [x] #11781 

## Global
- [x] #11719
- [x] #11288

**Comment by alaibe** [comment]
@benjthayer @John-44 In the design, what we should do in case of "stop using keycard"

**Comment by alaibe** [comment]
@benjthayer @John-44 what should be the flow in case of Remove keypair and associated accounts?

**Comment by saledjenic** [comment]
> what should be the flow in case of Remove keypair and associated accounts?

Seems it got added in meantime, I logged an issue for that https://github.com/status-im/status-desktop/issues/11734. We have the functionality in place, just need to align UI to match the Figma.
