### ISSUE TITLE
[EPIC] TokenMaster and Owner token Backend

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#11249]
### Description

Epic for all the backend work needed for the TokenMaster and Owner token work.

Design for reference https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=33640%3A574100&mode=dev

### Issues:

- [x] https://github.com/status-im/status-desktop/issues/11250
- [x] https://github.com/status-im/status-desktop/issues/11275
- [x] https://github.com/status-im/status-desktop/issues/11276
- [x] https://github.com/status-im/status-desktop/issues/11610
- [x] https://github.com/status-im/status-desktop/issues/11611
- [x] https://github.com/status-im/status-desktop/issues/11874
- [x] https://github.com/status-im/status-desktop/issues/11943
- [x] https://github.com/status-im/status-desktop/issues/11944
- [x] https://github.com/status-im/status-desktop/issues/11946
- [x] https://github.com/status-im/status-desktop/issues/11947

**Comment by anastasiyaig** [comment]
@glitchminer @lukaszso this is an EPIC which is now complete. Could u please take latest master and go through the tasks in this epic and check if everything listed works fine in master? No need to keep this task open though

**Comment by mprakhov** [comment]
@anastasiyaig, sorry, I was a bit hurry, I need to build a version with a correct status-go code

**Comment by anastasiyaig** [comment]
ah okay, please ping Lukasz and Magnus when ready ! Or me :)

**Comment by mprakhov** [comment]
this is an EPIC which is now complete. Could u please take latest master and go through the tasks in this epic and check if everything listed works fine in master?
cc @anastasiyaig , @lukaszso, @glitchminer

**Comment by lukaszso** [comment]
LGTM, i've checked happy paths only. We'll test it more thoroughly in RC.
