### ISSUE TITLE
[EPIC] [Community Ownership] Transfer tokenized community ownership

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#11370]
Nowadays, anyone with access to a community's private key is considered a control node. To import a community, one needs to transfer this private key across clients, which is problematic for many reasons.

Community ownership should be tokenized, i.e., bound to the owner of the Owner Token. To accomplish this, community updates should be signed not by the community's private key, but by the signer specified by the holder of the Owner Token.

- How is community ownership transferred?
Transfer the Owner Token to another account. Once this account receives the Owner Token, it needs to set a new signer using `ownerToken.setSigner(...)`.
- How do clients know who the signer of the community updates should be?
If the community has an Owner Token assigned, then the signer is identified by `ownerToken.getSigner()`. If not, the signer is the community itself.
- Why is the concept of `setSigner/getSigner` necessary? Couldn't we simply check the signature against the holder of the Owner Token?
This concept enables the establishment of a control node without needing to import the wallet containing the Owner Token.
- How can clients trust the Owner Token address bound to a given community?
The Owner Token must be deployed through a `CommunityTokenDeployer` contract. This entity manages an `CommunityOwnerTokenRegistry`, where the addresses of Owner Tokens for each community are stored. For more details, see: https://github.com/status-im/status-desktop/issues/11954#issuecomment-1709964605.

Tasks:
- [x] [Community Ownership] extend Owner Token contract with `setSigner/getSigner` API
- [x] #11954
- [x] #11956
- [x] #11957
- [x] #11958
- [x] #11964
- [x] #11963
- [x] #11961
- [x] #11962
- [x] #11969
- [x] #11974
- [x] #11945
- [x] #12175
- [x] https://github.com/status-im/status-desktop/issues/12656
- [x] Have a QA test the Epic as a whole

Spikes:
- [x] #11371

Things that may be affected and need to be checked:
- ~~new URL format, is the data signed with community's private key? ([details](https://github.com/status-im/status-desktop/issues/11371#issuecomment-1624206189))~~
- archive protocol ([details](https://github.com/status-im/status-desktop/issues/11371#issuecomment-1624206189))

Please update the epic status to QA when it is ready for testing

__QA Tasks__

- [x] QA epic https://github.com/status-im/desktop-qa-automation/issues/132

**Comment by John-44** [comment]
@benjthayer to post designs here when they are ready

**Comment by osmaczko** [comment]
FIGMA: https://www.figma.com/file/uHwhhUsne96HBhkunsD7Po/WIP-flows?type=design&mode=design&t=A7c5EuBzf4fQzFR9-0

**Comment by benjthayer** [comment]
All finalised flows relating to Community ownership have now been migrated over to the relevant places in the new Kuba Communities Figma file. (This file has been setup to house all of the Kuba Communities flows so they can be removed from the original Kuba file which is struggling with memory issues due to it's size). The relevant flows are:

Minting the Owner and TokenMaster tokens:
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=36893-637909&mode=design&t=jJiJOfDMZRslL1Wp-4

Transferring community ownership by sending the community's Owner token:
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=37206-87148&mode=design&t=jJiJOfDMZRslL1Wp-4

Changing the desktop device the Owner uses as their control node:
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=36894-684461&mode=design&t=jJiJOfDMZRslL1Wp-4
