### ISSUE TITLE
[EPIC] Collectibles improvements

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#11379]
### Description

- [x] #11558
- [x] https://github.com/status-im/status-desktop/issues/10728
- [x] #11782
- [x] https://github.com/status-im/status-desktop/issues/10467
- [x] #11592
- [x] #11635
- [x] #11651
- [x] Remove Collectibles service
- [x] #11788
- [x] #11637
- [x] #11785
- [x] #11899
- [x] #12159
- [x] #12150
- [x] #11636
- [x] https://github.com/status-im/status-desktop/issues/9823
- [x] #11800
- [x] #12311
- [x] #13721
- [x] https://github.com/status-im/status-desktop/issues/9832
- [x] #11802
- [ ] Collecitble Details loading animation
- [x] #12312
- [x] #11638
- [x] #12310
- [x] #12309
- [x] #12352
- [x] #12338
- [x] #12399
- [x] #12521
- [x] #12494
- [x] #12771
- [x] #12937
- [x] #13022
- [x] #13025
