### ISSUE TITLE
Epic: get Deploy Community Directory Curation dApp deployed

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#11461]
Moving this out of the 0.13 milestone notes into an issue.

**Deploy Community Directory Curation dApp**
- [x] Deploy SNT contract to Optimism
- [x] Register SNT contract with Optimism bridge
- [x] Deploy Curation dApp smart contracts to Optimism mainnet (not testnet)
- [x] Deploy Community Directory Curation dApp UI to "curate.status.app" domain (task for PVL)
- [ ] Have a QA test the Epic as a whole

Then create a public 'Status Test Community' as soon as 0.13 final is released
- 1 SNT is required to join the community
- The community contains some token gated channels
- Mint soulbound remotely destructible admin token
- Airdrop Admin token to everybody in Messaging, QA and UI teams 
- Setup admin permission

Start vote for this community to be the first community featured in the real, mainnet Community Directory!

Please update the epic status to QA when it is ready for testing

- [x] #12569

__QA Tasks__

- [ ] QA epic https://github.com/status-im/desktop-qa-automation/issues/135

**Comment by osmaczko** [comment]
On hold. The deployment of SNT on Optimism has been postponed due to security considerations.

**Comment by jrainville** [comment]
Closing as done. QAs have a task in their repo to test
