### ISSUE TITLE
[EPIC] Discord history import into a single channel in an existing community 

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12018]
### Description

- Pay off any Discord history import service tech. debt first
- Then build the import into a single channel functionality, designs for this are already complete

Design: https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=36964-193302&mode=design&t=CBuCXCtGTLkYBeW6-0

#### Front-end
- [x] https://github.com/status-im/status-desktop/issues/12039
- [x] https://github.com/status-im/status-desktop/issues/12239
- [ ] Post creation:
  - [ ] :new: Display a channel tooltip ("Your channel is ready")
  - [ ] :new: Display a floating in-chat banner ("The channel was imported...")
- [ ] Minor improvements:
  - [x] https://github.com/status-im/status-desktop/issues/12099

#### Back-end

- [x] https://github.com/status-im/status-desktop/issues/12238
- [x] https://github.com/status-im/status-desktop/issues/12503
- [x] https://github.com/status-im/status-desktop/issues/12504
- [x] https://github.com/status-im/status-desktop/issues/8522
- [x] https://github.com/status-im/status-desktop/issues/8589

Please update the epic status to QA when it is ready for testing

__QA Tasks__

- [ ] QA epic https://github.com/status-im/desktop-qa-automation/issues/133

**Comment by alexjba** [comment]
@borismelnik I've added this task to improve the error messages we see in the UI. Looks like it's partially backend - partially UI. WDYT, is it something we can do as part of this epic?

https://github.com/status-im/status-desktop/issues/12098

**Comment by borismelnik** [comment]
> @borismelnik I've added this task to improve the error messages we see in the UI. Looks like it's partially backend - partially UI. WDYT, is it something we can do as part of this epic?
> 
> #12098

Sure, why not :)

**Comment by iurimatias** [comment]
this should be done for 0.15

**Comment by iurimatias** [comment]
descoped for now
