### ISSUE TITLE
Can't see fresh sent/received in activity

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#12077]
### Description

I sent some ETH tokens and figured out that after the transaction is confirmed, it doesn't show in all or any of the account's activity filter.

### Findings

It seems the multi-transaction is missing "to" and "from" network IDs, which are `0` in DB. This, in combination with the filter not using "all networks" API, filters out the multi-transaction entry.

`SELECT HEX(from_address), HEX(to_address), HEX(from_amount), from_network_id, to_network_id, timestamp, ROWID FROM multi_transactions ORDER BY timestamp DESC LIMIT 5;
E2D622C817878DA5143BBE06866CA8E35273BA8A|5D7905390B77A937AE8C444AA8BF7FA9A6A7DBA0|307865386434613531303030|0|0|1693839242|1149`

The latest changes to `CreateMultiTransactionFromCommand` are missing forwarding the NetworkID.

### TODO

- [x] Send empty chain IDs instead of all entries when we don't want to filter for specific chain IDs [#12078](https://github.com/status-im/status-desktop/pull/12078)
- [x] Fix showing multi_transactions as pending, found after implementing all chains fix
  - The query dos need at least a sub-transaction to be in transfers to show completed or failed. Fixed by https://github.com/status-im/status-go/pull/3987
  - Improved https://github.com/status-im/status-go/pull/3987
- [x] Propagate chain IDs to multi-transaction when available https://github.com/status-im/status-go/pull/3994
