### ISSUE TITLE
[EPIC][Community Ownership] UI flows for sending owner token

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#12087]
### Description
[Design](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=37206%3A87025&mode=design&t=Bz2sh1phXuTgl7SY-1)

- [x] https://github.com/status-im/status-desktop/issues/12171
- [x] https://github.com/status-im/status-desktop/issues/12172
- [x] https://github.com/status-im/status-desktop/issues/12173
- [x] https://github.com/status-im/status-desktop/issues/12174
- [x] https://github.com/status-im/status-desktop/issues/12175

Please update the epic status to QA when it is ready for testing

__QA Tasks__

- [x] QA epic https://github.com/status-im/desktop-qa-automation/issues/132

**Comment by noeliaSD** [comment]
After an offline conversation with @benjthayer this task keeps pending of new design confirmation. It will be updated once we have a final decision taken.

**Comment by noeliaSD** [comment]
Finally there are no changes on the design so, the original flow can be develped!

**Comment by noeliaSD** [comment]
Required backend integration task: https://github.com/status-im/status-desktop/issues/12155

**Comment by noeliaSD** [comment]
Once [this task ](https://github.com/status-im/status-desktop/issues/12656) is integrated, the epic can be moved to QA status.

cc: @glitchminer
