### ISSUE TITLE
[Epic][Link previews][UI] Implement the new link preview design

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12178]
### Description

[Design](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?type=design&node-id=3009-26826&mode=design&t=HFbxcAs9InjfzBHr-0)

The main change in the link previews is that the preview will be fetched on sender side and will be sent as a message to the receiver. It means the receiver will be able to see all the preview information without reaching to the received URL to fetch and process the preview. This is a simplification for the UI flows because the link previews are available immediately when the preview is created and there should be no need to fetch other info on-demand.

We can split the new design in two:

1. [Link preview in messages view](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?type=design&node-id=22347-219483&mode=design&t=eO0q9IYam0gBUZoF-0):
- [x] https://github.com/status-im/status-desktop/issues/10585 The new cards will be used both for sender and receiver link preview. The only difference is the callout tail direction.
- [x] #12179
- [x] #12176
- [x] #12183
- [x] ~#12389~
- [x] #12388
- [x] #12382
- [x] #12444

2. [Link preview in chat input](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?type=design&node-id=22341-102457&mode=design&t=eO0q9IYam0gBUZoF-0):
- [x] #12180
- [x] #12181
- [x] #12398

3. [Link preview in settings](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?type=design&node-id=23650-116367&mode=design&t=7IZmhnse7ELoQRHu-0)
- [x] #12397
- [x] https://github.com/status-im/status-desktop/issues/10864
- [x] https://github.com/status-im/status-desktop/issues/12442

This Epic depends on the following tasks:
- https://github.com/status-im/status-mobile/issues?q=is%3Aopen+is%3Aissue+label%3A%22E%3AMobile+URL+Preview+MVP%22
- https://github.com/status-im/status-go/issues/3761
- https://github.com/status-im/status-go/issues/3762
- https://github.com/status-im/status-go/issues/4132

Please update the epic status to QA when it is ready for testing

__QA Tasks__ 
- [ ] QA epic is complete https://github.com/status-im/desktop-qa-automation/issues/130

**Comment by lukaszso** [comment]
Test cases were created, happy paths tested, i've also added a task to create automated tests for this feature. Closing.
