### ISSUE TITLE
[EPIC] Open `status.app` links

### ISSUE THREAD

**Issue by borismelnik** [status-im/status-desktop#12245]
### Description

That issue about to new link formats, universal links and deeplinks.

Depends on:

- [x] https://github.com/status-im/status-desktop/issues/10851
- [x] https://github.com/status-im/status-desktop/issues/10852
- [x] https://github.com/status-im/status-go/pull/3855
- [x] https://github.com/status-im/status-desktop/issues/7957
- [x] https://github.com/status-im/status-desktop/issues/9549
- [ ] https://github.com/status-im/status-desktop/issues/8027
- [ ] https://github.com/vacp2p/rfc/pull/602
- [ ] https://github.com/vacp2p/rfc/pull/600
- [ ] https://www.figma.com/file/Nt3KJ8AXm0VPpIRLxaHnw0/Sharing-for-Mobile
- [ ] Have a QA test the Epic as a whole

### Acceptance Criteria

- Make sure that all links open the app in the correct locations (link to community should open the community, links to accounts should open the user profile and so on)
- Make sure that ways like universal links or deep links on all supported platforms opens the app in the current location

**Comment by jrainville** [comment]
Closing as stale. The remaining task can be done independently
