### ISSUE TITLE
Include watch only per account

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#12305]
Goal is to control per account which watch address is being displayed

Design: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=19218-313442&mode=design&t=HnNmumCrgH8Vl23C-0

## Settings UI
- [x] Backend - add to account table a boolean about visible or not
- [x] Remove global toggle for wallet account
- [x] On update account add the switch to update if watch only is visible or not

## Main wallet account UI
- [x] Remove toggle in main wallet all account view
- [x] Add context menu for watch only account to display or not in total balance
- [ ] Calculation for all account  in assets / collectibles / activity depends of watch only account being visible or not
