### ISSUE TITLE
Investigate the best way to implement Wallet Connect v2 in Status-Desktop

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#12301]
# Wallet Connect v2

## Prototype

- [x] Integrate web SDK in WebView
- [x] Communicate externally to forward actions and propagate events to/from the wallet
  - [x] offline (no web server) was demonstrated using `WebView.runJavaScript` and a `Timer` for a pooling behaviour.
  - [x] ~~webserver might provide a simpler reactive alternative but with higher risk of exposing a webserver with a specific port to the environment~
    - The pooling workaround seems to work fine and reliable
- [x] Move prototype code to nim APP

## Implementation

Options

- WebView + Web SDK
  - not sure if it is properly supported on all platforms without relaying on the heavy Qt WebEngine
- Cross-platform library
  - It looks like there is no option. There is a [rust SDK](https://github.com/WalletConnect/WalletConnectRust/tree/main) in the work, but no guarantee it will be usable for cross-compilation

## Info

Web3Wallet SDK ([web3wallet](https://github.com/WalletConnect/walletconnect-monorepo/tree/v2.0/packages/web3wallet))

- Web
- iOS (Swift)
- Flutter
- React Native
- C#

The client SDKs are supported in the "Web3Modal SDK"

- React + wagmi (react hooks for ethereum)
- Vue + wagmi
- HTML + wagmi
- Flutter
- Android

## User Flow

[Overview](https://specs.walletconnect.com/2.0/specs/clients/sign/session-proposal)

Integration steps

```mermaid
sequenceDiagram
  participant dApp
  participant WalletConnect
  participant StatusWallet

  dApp->>WalletConnect: Request Connection
  WalletConnect->>StatusWallet: Show QR Code / Deep Link
  StatusWallet->>WalletConnect: Scan QR Code / Follow Deep Link
  WalletConnect->>dApp: Confirm Connection

  dApp->>WalletConnect: Send Transaction Request
  WalletConnect->>StatusWallet: Push Notification (Approve/Reject)
  StatusWallet->>WalletConnect: Approve Transaction
  WalletConnect->>dApp: Confirm Transaction
```

UX steps

1. App displays qrcode or **deep link** to connect wallet
2. User scans qrcode or **redirects to wallet**
3. User approves session proposal from App
4. User returns to app after success prompt
5. App receives accounts and namespaces from Wallet
6. App sends request to sign transaction or message
7. User redirects to wallet to inspect request
8. User approves transaction or message request
9. User returns to app after success prompt
10. App receives transaction confirmation or signature

## APIS

Sign - establishes a session between a dapp and a wallet in order to expose a set of blockchain accounts that can sign transactions

Auth - simple and lean interface to enable applications to authenticate wallet users to login/signin into applications with their wallets by automatically signing an authentication message.

Verify - allows wallets to notify end-users when they may be connecting to a suspicious or malicious domain, helping to prevent phishing attacks across the industry.

**Comment by stefandunca** [comment]
Following my Wallet Connect integration and QML prototype, here are my latest findings and understanding:

- The closest option for desktop is to use the **Web Wallet SDK** via QML's *WebView*
  - Alternatively, a closer-to-native experience can be achieved by integrating a `NodeJS` library in the app and executing the web SDK internally. However, the complexity, risks and maintenance burden are too high and not worth given that Mobile has react-native SDKs
- The major limitation is that the integrated web view has to be visible to process Wallet Connect events, which can be done in one of two ways
  - **QML UX**: embed and "hide" the `WebView` in the WalletConnect modal popup by filling it with background
    - This allows us to provide a **Status themed** wallet-connect integration
    - This can have side effects (an HTML error might appear in some corner cases in the web view)
    - Mixing WebView (web controls) with QML controls is not possible so the web view will be posted at the bottom without any content and background colour matching the QML's modal
    - More complexity on the wallet integration side
  - **HTML UX**: Use a web browser HTML5 interface
    - This limits the UX experience by providing a non-themed visual experience
    - Might be easier to integrate with the SDK, allowing a lighter wallet integration
    - More maintenance burden due to the HTML code
- Other limitations:
  - Could not make the "offline" bundle work to load from disk; providing an in-process web server might be necessary.
  - Will require another build step (could be made)

Some more background:

- The Wallet Connect doesn't provide any desktop platform native SDKs
  - There is a client-side attempt in Rust, but it is not production-ready, and no wallet integration support

**Comment by stefandunca** [comment]
> ...
> Once page is loaded we should have a full access to DOM and we can change anything we want, like colors, links, edit the page, interact with the page from the qml, so I am pretty sure all interactions should be possible.

I meant the mix between QML controls and WebView as specified in [Qt's documentation](https://doc.qt.io/qt-5/qml-qtwebview-webview.html#details) "Note: Due to platform limitations overlapping the WebView and other QML components is not supported."
