### ISSUE TITLE
Wallet: explore streamlining the various wallet models spread across different sections

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#12424]
### Description
 Using this task to explore how we can improve the wallet modules across sections such as Browser, Wallet, Community, Settings etc.

Currently we have seprate models in settings, community and wallet , however some of these could be shared. This task will used as a place to explore possible options and find a solution that works best.

**Comment by noeliaSD** [comment]
We’ve started the exploration understanding which are the **use cases** consumers of data coming from `src/app_service/service/token/service.nim` and also which is the data coming from it (being this data all **pure list of tokens** from **supported app sources** (nowadays _uniswap, status_ and _custom_ lists)).

**App use cases:**
-
Definition of app use cases in a high level way:
- To add new `permission` in a community via `Holding dropdown`.
- To validate and avoid repetition of `name` and `symbol` whenever a new community token is minted.
- To display all tokens from a specific source in `Wallet / Settings / Manage tokens / Tokens List Tab`.

**Goal:**
-
All of these use cases will need the same data source but UI representation will be different, so the aim of this analysis is:
- Identify if service can present data in a better/easy/basic and generic way and try to avoid data filtering at this point if it’s just a visual representation issue. 
- Identify which are the models needed and try to minimise them designing them in a way that they can be reused across different views avoiding repetition of code and uncertainty when deciding which is the real source of information for each use case. Models should relay only in 1 source of truth, that means, data provided by the service.
- Analyse current stores definition, only the ones affected by the specific service use cases, and expose the new models in a single place.

**Subtasks:**
-
 Here the subtasks needed to go through and work on all explained points:
- [ ] Definition of new service, wallet submodule, controller, view and models (flat tokens list and by symbol tokens list). Also add these new models in the correct qml `store`:  [Ongoing draft PR ](https://github.com/status-im/status-desktop/pull/12489)
- [ ] `TokenType` Enum unification accross all app layers (including nim and qml code)
- [ ] Generic Cpp model class for dealing with joins in UI layer
- [ ] Replace existing model used in `Community / Permissions` and do the needed cleanups
- [ ] TBD

**NOTE:** After this example is fully covered, next step will be exploring `src/app_service/service/wallet_account/service.nim` and try to follow same approach.
