### ISSUE TITLE
EPIC: Revive Telemetry service and improve it

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12429]
### Description

We have a service that's called the Telemetry service which helps us measure the reliability of the network and to see if clients correctly receive messages.

Right now, most people don't have it activated (it's a switch in Advanced). Also, it could be improved to help us understand if envelopes when received are processed correctly.

#### Resources:

- Telemetry repo: https://github.com/status-im/telemetry
- Status-go code: https://github.com/status-im/status-go/blob/54928bd7f503b7b3c18eaaeb2bd6758f0617bafa/protocol/messenger.go#L3585-L3587

### Tasks:

- [x] https://github.com/status-im/status-desktop/issues/12430
- [x] https://github.com/status-im/status-desktop/issues/12431
- [x] https://github.com/status-im/infra-misc/issues/181

Please update the epic status to QA when it is ready for testing

**Comment by jrainville** [comment]
Closing as done. QAs have a task to track the testing
