### ISSUE TITLE
WalletConnect: report transactions as between user and dApp

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#12782]
### TODO

Activity UX:

- The user should see the entry in activity as `dapp`
- The user should see the sign method of WalletConnect

#### Technical requirements

For `session_request` of send transactions

- [ ] Add to `multi_transactions` table
- [ ] Track transaction to trigger downloader and link for activity entry
- [ ] Register sign as WalletConnect
- [ ] Link with dapp list

### History

From Ben:

"... it would work like the transactions we currently have in the wallet activity flows for wallet interactions with 3rd party (external) exchanges:

Eg:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=15324-456837&mode=design&t=1jdoSrZs2pptRmus-4

In these instances, a buy Tx is shown as a receive Tx (from the exchange/dApp) given that is the end result to the user wallet and a sell Tx is a send Tx (to the exchange/dApp) - again that is the end result to the wallet. 

In these instances we also show the Tx only when there is 1 confirmation on Mainnet - no pending state. The only difference here is that we could show the Signing method section of the activity detail page because the signing event has been executed on Status desktop."

**Comment by dlipicar** [comment]
@benjthayer waiting for new designs. Please add the link here when they're ready

**Comment by stefandunca** [comment]
Closing this given that new design shows that we need a more thorough thinking of the approach in case of activity for general dApps that also cover Wallet Connect.
