### ISSUE TITLE
[EPIC] Encrypt sensitive information in the Community Description

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12850]
### Tasks

- [x] https://github.com/status-im/status-desktop/issues/12851
- [x] https://github.com/status-im/status-desktop/issues/12852
- [x] https://github.com/status-im/status-desktop/issues/12853
- [ ]  Have a QA test the Epic as a whole

**Comment by osmaczko** [comment]
Thanks for creating it :pray:

**Comment by osmaczko** [comment]
This is not testable by QAs as there is an overlay screen when community/channel token requirements are not met and so they can't check whether chats/members list is empty or not.
