### ISSUE TITLE
[Epic] Profile Showcase

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12984]
# [WIP Design](https://www.figma.com/file/d0G7m8X6ELjQlFOEKQpn1g/Profile-WIP?type=design&node-id=1-13865&mode=design&t=gxavA5yTTwXWFu9s-0) - [Actual Design](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-8755&mode=design&t=jumwFduKExodhRUc-0)

## Bugs
- [x] #13329
- [ ] https://github.com/status-im/status-desktop/issues/13754

## General

- [x] #13330
- [x] #13406
- [x] #13331
- [x] #13332
- [x] #13333
- [x] #13334
- [x] https://github.com/status-im/status-desktop/issues/13504
- [x] https://github.com/status-im/status-desktop/issues/13507
- [x] https://github.com/status-im/status-desktop/issues/13508
- [x] #13682
- [x] https://github.com/status-im/status-desktop/issues/13509
- [x] https://github.com/status-im/status-desktop/issues/13595
- [x] https://github.com/status-im/status-desktop/issues/13594
- [ ] https://github.com/status-im/status-desktop/issues/13515
- [ ] https://github.com/status-im/status-desktop/issues/13516
- [x] https://github.com/status-im/status-desktop/issues/13517
- [x] https://github.com/status-im/status-desktop/issues/13678
- [x] #13941

## Identity
~~- [ ] #13350~~ out of scope for MVP, to be done in the next milestone
- [x] #13351
- [x] #13335 

## Assets

- [x] #13336 
- [x] #13337 
- [x] #13338 
- [x] #13681

Pending assets tasks will be covert by the following EPIC:
- [ ] https://github.com/status-im/status-desktop/issues/14367

## Collectibles

- [x] #13340 
- [x] #13462
- [x] #13342 
- [x] https://github.com/status-im/status-desktop/issues/13680

## Accounts
- [x] https://github.com/status-im/status-desktop/issues/13899

## Web
- [x] https://github.com/status-im/status-desktop/issues/13511

## Profile Popup
Meaning it as the popup shown when `previewing` but also the popup shown when looking at someone's `profile`.
- [x] #13416
- [ ] #13420
- [x] #13606
- [x] #13421
- [x] #13702
- [x] #13417
~~- [ ] #13418~~ out of scope for MVP, to be done in the next milestone
- [ ] #13423
- [x] #13424
- [x] #13479
- [x] #13480
- [x] #13482
- [x] #14014 
- [x] #14015 
- [ ] #14227
- [ ] #14238
- [x] #14264
## Profile popup / contact interactions
Separate epic: https://github.com/status-im/status-desktop/issues/13500

## Password
- [x] [Password Change Page](https://github.com/status-im/status-desktop/issues/10037) | [Design](https://www.figma.com/file/d0G7m8X6ELjQlFOEKQpn1g/Profile-WIP?type=design&node-id=11-106858&mode=design&t=LfjKQR8CpUCKFQ3v-4)

**Comment by noeliaSD** [comment]
Backend related EPIC: https://github.com/status-im/status-desktop/issues/12658

**Comment by alexandraB99** [comment]
Updated backend EPIC: https://github.com/status-im/status-desktop/issues/13069

**Comment by alexjba** [comment]
@jrainville Based on the new [designs](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/👤-Profile-%7C-Desktop?type=design&node-id=2460-203020&mode=design&t=JQQujj91n0kMpCFr-0) when blocking a contact, the DB is purged of any messages previously received by the contact in any context. I see this doesn't happen at the moment, and looks to me like we need a backend implementation for this. Do you know if it's already implemented or planned?

**Comment by jrainville** [comment]
> @jrainville Based on the new [designs](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-203020&mode=design&t=JQQujj91n0kMpCFr-0) when blocking a contact, the DB is purged of any messages previously received by the contact in any context. I see this doesn't happen at the moment, and looks to me like we need a backend implementation for this. Do you know if it's already implemented or planned?

@alexjba @mprakhov is already working on that. Here https://github.com/status-im/status-desktop/issues/13034 and here https://github.com/status-im/status-desktop/issues/13453

**Comment by jrainville** [comment]
> Does it mean, that in your scenario you need to remove all user messages (for a client, who is blocking) from all communities and 1 to 1 msgs?

Ah my bad, those are two different issues. @mprakhov is working on banning from a community.

As for blocking a user, it's a different issue.This is not exactly the right issue, but it does concern what happens when one person blocks another https://github.com/status-im/status-desktop/issues/8975

So back to your original question @alexjba 

> Do you know if it's already implemented or planned?

Yes it is planned at some point. I don't think it's implemented yet.

**Comment by caybro** [comment]
> I'm working on removing all user messages from the community (during member ban) Does it mean, that in your scenario you need to remove all user messages (for a client, who is blocking) from all communities and 1 to 1 msgs?

Not sure about ban, but blocking somebody should go like this:
![image](https://github.com/status-im/status-desktop/assets/5377645/68df683e-3da4-4814-b595-44c34e9d8cd6)

**Comment by jrainville** [comment]
We can implement the backend for it for the context shown above. It shouldn't be too complex.

As for the other issue about blocking a user and being removed from all the chats and such, we can do that later.

@alexjba or whoever, feel free to open an issue for it and ping me so that I can assign it.
