### ISSUE TITLE
[Epic] Bridge Status/Discord

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#13256]
* [x] https://github.com/status-im/status-desktop/issues/12710
* [x] https://github.com/status-im/status-desktop/issues/13098
* [x] https://github.com/status-im/status-desktop/issues/13257
* [x] https://github.com/status-im/status-desktop/issues/13353
* [x] https://github.com/status-im/status-desktop/issues/13736
* [ ] https://github.com/status-im/status-desktop/issues/13251
* [x] https://github.com/status-im/status-desktop/issues/13258

Matterbridge branch: https://github.com/status-im/matterbridge/tree/waku2

**Comment by anastasiyaig** [comment]
i am reopening this as there are inner tasks to be finished before this epic can be closed
