### ISSUE TITLE
Bugs/Stabilization for 0.17

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#13268]
Parent epic for stabilization of 0.17

- [x] https://github.com/status-im/status-desktop/issues/12496
- [x] https://github.com/status-im/status-desktop/issues/13135
- [x] https://github.com/status-im/status-desktop/issues/13219
- [x] https://github.com/status-im/status-desktop/issues/13266
- [x] https://github.com/status-im/status-desktop/issues/13198
- [x] https://github.com/status-im/status-desktop/issues/12693
- [x] https://github.com/status-im/status-desktop/issues/13249
- [x] https://github.com/status-im/status-desktop/issues/11757
- [x] https://github.com/status-im/status-desktop/issues/11670
- [ ] https://github.com/status-im/status-desktop/issues/12275
- [x] https://github.com/status-im/status-desktop/issues/9567
- [x] #13326
