### ISSUE TITLE
[MILESTONE_GOAL] 2.28 - Profile Showcase

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#13304]
### Description

Continue work on profile showcase

### Tasks

- [ ] https://github.com/status-im/status-desktop/issues/13069
- [x] https://github.com/status-im/status-desktop/issues/13072
- [x] https://github.com/status-im/status-desktop/issues/13075
- [x] https://github.com/status-im/status-desktop/issues/13076
- [x] https://github.com/status-im/status-desktop/issues/13080
- [x] https://github.com/status-im/status-desktop/issues/13081
- [x] https://github.com/status-im/status-desktop/issues/13082
- [x] https://github.com/status-im/status-desktop/issues/13083
