### ISSUE TITLE
[EPIC] Send ERC1155

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#13428]
Collectible may have multiple occurrences and as such support 1155 in Send

- [x] #13433
- [x] #13429
- [x] #13450
- [x] integration with new collectible contract https://github.com/status-im/communities-contracts/pull/45
- [x] [Render erc1155 in groups](https://github.com/status-im/status-desktop/issues/12940)
- [x] Render erc721 collectible in groups
- [x] #13797
- [x] https://github.com/status-im/status-desktop/issues/13399
- [x] https://github.com/status-im/status-desktop/issues/13731
- [x] #14251
