### ISSUE TITLE
[Epic] Profile interactions/flows

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#13500]
## Profile popup / contact interactions
Figma: https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-197035&mode=design&t=PinU3PVz9XZkigA6-0

- review these flows, we should have all of the needed backends for this, including most of the popups
- unify the secondary dialogs to have the same look (common profile header) :new: 
- add necessary auxiliary actions to those popups (e.g. when untrusting someone -> add block) :new: 
- verify at any given state we have the correct entries in ProfileContextMenu.qml and the profile dialog's menu
- emit appropriate notification/toast upon performing the action :new:

The flows:
- [x] #13513
- [x] #13518
- [x] #13519
- [x] #13520
- [x] #13521
- [x] #13522
- [x] #13711
- [x] #13709
- [x] #13591

Backend:
- [x] https://github.com/status-im/status-desktop/issues/13604
- [x] https://github.com/status-im/status-desktop/issues/13716

Bugs:
- [x] https://github.com/status-im/status-desktop/issues/13870

**Comment by caybro** [comment]
This is completed from both dev and QA POV
