### ISSUE TITLE
[EPIC] [ProfileShowcase] Move the dirty state management to C++/qml

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13798]
### Description

*Summary*: Moving the dirty states management from nim to c++/qml to simplify the data flows and overcome current challenges. 

The desired UI dataflow is depicted here:
https://miro.com/app/board/uXjVNxUvgDA=/#

The QML/C++ layer will receive minimal models for each tab: `Communities`, `Accounts`, `Collectibles`, `Assets`, `Web` and will join these models with the app data for each tab to properly display all the needed information. The dirty state handling will be done by the QML/C++ layer using the current proxies as main building blocks. The next interaction with the nim layer will be just on save when all the necessary data for this operation is collected by the QML/C++ and passed to nim.

### Acceptance Criteria

Technical specs:
1. The nim layer is reduced to support only 3 operations: Exposing the profile showcase settings, updating the settings with network events (synced data between accounts), saving all the profile showcase settings in one shot.
2. The QML/C++ layer implements the building blocks needed to display the profile showcase data as depicted in the miro design.

Tasks:

- [x] https://github.com/status-im/status-desktop/issues/13498
- [x] #13799
- [x] #13800
- [x] #13801
- [x] https://github.com/status-im/status-desktop/issues/13495
- [x] https://github.com/status-im/status-desktop/issues/13603
- [x] https://github.com/status-im/status-desktop/issues/13494
- [x] https://github.com/status-im/status-desktop/issues/13490
- [x] https://github.com/status-im/status-desktop/issues/13402
- [x] https://github.com/status-im/status-desktop/issues/13341
- [x] https://github.com/status-im/status-desktop/issues/13638
- [x] https://github.com/status-im/status-desktop/issues/13602
- [x] https://github.com/status-im/status-desktop/issues/13683

**Comment by noeliaSD** [comment]
The missing **assets** tasks will be tracked in a separate epic so this one can be considered as closed! Great job @alexjba @micieslak !!
