### ISSUE TITLE
[Epic] Profile Showcase Assets

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14367]
### Description

[Assets settings / preferences](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460%3A35975&mode=design&t=oMr7Kif8RulfDm1I-1)
![Screenshot 2024-04-09 at 12 56 53](https://github.com/status-im/status-desktop/assets/97019400/f97c47db-748f-4f61-8c6f-da0083a99447)

[Assets for a contact depending on account selection](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460%3A37298&mode=design&t=oMr7Kif8RulfDm1I-1)
![Screenshot 2024-04-09 at 13 03 15](https://github.com/status-im/status-desktop/assets/97019400/96c87e8d-c3db-4a8e-a1a3-c47f7d499747)

Some basic _user stories_ of the feature:
- The user must be able to publish her/his owned wallet assets to other users with different levels of visibility
- Assets can be part of the supported tokens list and / or community minted assets.
- The user must be able to see the total balance of an asset published by another user if it's part of the public profile.

Here the list of pending tasks related to `Profile Showcase Assets` _settings_ AND _contact profile_.

They are included all **UI**, **backend** and interconnection with **wallet** tasks needed to complete the epic:

## UI layer tasks 
They must be taken in order:
- [x] https://github.com/status-im/status-desktop/issues/14370
- [ ] https://github.com/status-im/status-desktop/issues/13492
- [ ] https://github.com/status-im/status-desktop/issues/14375

Dependent on previous ones (can be done in parallel):
- [ ] https://github.com/status-im/status-desktop/issues/13679
- [ ] https://github.com/status-im/status-desktop/issues/13339
- [ ] https://github.com/status-im/status-desktop/issues/13343

Related to profile contact:
- [ ] #14384

## Backend layer tasks
- [x] https://github.com/status-im/status-desktop/issues/14129

 ## Wallet interaction tasks
- [ ] API to get metadata of a community token via the smart contract

 ## Misc
Previous relevant analysis tasks and results that can be useful to continue this feature development:

- https://github.com/status-im/status-desktop/issues/13462
- https://miro.com/app/board/uXjVNxUvgDA=/
- https://github.com/status-im/status-desktop/issues/13410
- https://github.com/status-im/status-desktop/issues/13798

**Comment by noeliaSD** [comment]
cc: @alexjba @micieslak please review the UI part and create missing tasks if you detect them
cc: @MishkaRogachev I've added the backend task you shared, if you want, we can use the same epic so we have everything packed here and we have a global view of the feature progress as a whole
cc: @Khushboo-dev-cpp here I've added a section of the wallet needs. Please add the missing tasks you also can detect.

**Comment by jrainville** [comment]
We won't be doing Assets in the Profile Showcase
