### ISSUE TITLE
[Profile Showcase - Assets] Prepare UI for receiving assets backend model

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14384]
### Description

Integrate the new models with the assets delegates from profile dialog view.

<img width="561" alt="Screenshot 2024-04-10 at 13 39 07" src="https://github.com/status-im/status-desktop/assets/47811206/1e9d62f1-5996-4387-8e3c-86b46792f2a3">

#### To do

- [ ] Uncomment the assets tab in profile dialog view
- [ ] Adapt the delegates to the new rolenames
- [ ] Filter the model based on the profile dialog view perspective selection
- [ ] Add a basic loading state for when the data is still processed by the backend
- [ ] Integrate the delegate interactions and context menu [FIGMA](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/👤-Profile-%7C-Desktop?type=design&node-id=2460-8755&mode=design&t=PnKyb5l3jVZHIjPI-0)

#### Tasks implementing the models

- [ ]  https://github.com/status-im/status-desktop/issues/14129
- [ ] https://github.com/status-im/status-desktop/issues/13492

**Comment by jrainville** [comment]
We won't be doing Assets in the Profile Showcase
