### ISSUE TITLE
Add Wallet Connect connection flow

### ISSUE THREAD

**Issue by clauxx** [status-im/status-desktop#14556]
### Description
_As a user, I want to connect to dApps so that they can send me signing requests in the future._

In order for the user to be able to receive signing requests (e.g. transactions), they should be able to connect to a dApp by pasting a URL. Design fidelity is not yet a priority, so we should aim for the simplest solution by using existing UI elements and focus on the UX.

[Design link](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=28-28851&mode=design&t=vDEK7XNRpW1HQBUi-4)

> NOTE: connecting via the "All accounts" screen is out of scope for this user story

### Acceptance Criteria

- [x] The user should have a "dApps" button on the wallet account screen
- [x] The user should see a placeholder for connected dApps after pressing the dApps button
- [x] The user should see a "Connect dApp ..." button below the placeholder
- [x] [#14590](https://github.com/status-im/status-desktop/pull/14590); The user should see an [input](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=28-28714&mode=design&t=vDEK7XNRpW1HQBUi-4) for adding the connection request url (and paste button if already available)
- [x] #14607
- [x] [#14615](https://github.com/status-im/status-desktop/pull/14615): The user should see a [success session dialog](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=481-165751&mode=design&t=vDEK7XNRpW1HQBUi-4) if connection was successful.
- [x] [#14615](https://github.com/status-im/status-desktop/pull/14615): The user should see a [failed session dialog](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=481-165959&mode=design&t=vDEK7XNRpW1HQBUi-4) if the connection failed.
- [x] [#14615](https://github.com/status-im/status-desktop/pull/14615): The user should be able to close the dialog.

[comment]: # (Rules for the future PR to be accepted.)

**Comment by stefandunca** [comment]
I moved `The user should see a notification if the connection was successful` to its own issue to be tackled with a lower priority https://github.com/status-im/status-desktop/issues/14754
