### ISSUE TITLE
[EPIC - dApps Connection] UI components and flows 

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14588]
### Description
Here there are covered all the UI details for all related _dApp connection_ flows defined in here:
[Design](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=311%3A39367&mode=design&t=8Ziy7FfR0cagjggI-1)

When the user story is done and ready for QA, we should: 
1.  mark it in the checklist as done
2. DON'T close the user story issue user story
3. change the status to QA in the user story issue
4. change the status to QA in the notion user story
5. leave a comment with a tag for the QA to see that it's ready for testing

- [x] #14589
### User stories - UI e2e flows
Prioritised user stories in [HERE](https://www.notion.so/Desktop-dApp-interactions-M1-bceeb5ad67734f509d2a187ec2ff8937)

- [x] https://github.com/status-im/status-desktop/issues/14678
- [x] https://github.com/status-im/status-desktop/issues/14755
- [x] https://github.com/status-im/status-desktop/issues/14756
- [x] https://github.com/status-im/status-desktop/issues/15057
- [x] #15673

### Ongoing integration tasks
- https://github.com/status-im/status-desktop/issues/14556
- https://github.com/status-im/status-desktop/issues/14557

### Improvements
- https://github.com/status-im/status-desktop/issues/15075
