### ISSUE TITLE
[EPIC] Issues that need to be checked once the Router is ready

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#14639]
Once we complete https://github.com/status-im/status-desktop/issues/14638 we have to check each of the issues below:

- [x] #11536
- [x] #11104
- [x] #12747 
- [x] #14078 
- [x] #14441 
- [x] #14513 
- [x] #14569 

New/similar/same issues:
https://docs.google.com/spreadsheets/d/11VY6A1cQgtTe0z3JOoUv6gWDPUGWYDdIiGzZXHaptfI/edit#gid=557840942

----
New issues from 24.07.2024:
- [x] https://github.com/status-im/status-desktop/issues/15699
- [x] https://github.com/status-im/status-desktop/issues/15725
- [x] https://github.com/status-im/status-desktop/issues/15700
- [x] https://github.com/status-im/status-desktop/issues/15701
- [x] https://github.com/status-im/status-desktop/issues/15722
- [x] https://github.com/status-im/status-desktop/issues/15723
- [x] https://github.com/status-im/status-desktop/issues/15726
- [x] https://github.com/status-im/status-desktop/issues/15720
- [x] https://github.com/status-im/status-desktop/issues/15697
- [x] https://github.com/status-im/status-desktop/issues/15762
- [x] https://github.com/status-im/status-desktop/issues/15763
