### ISSUE TITLE
[UI - dapps Connection]  dApp URL validation errors

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14676]
[Design](https://www.figma.com/file/HrmZp1y4S77QJezRFRl6ku/Descoped-dApp-Interactions?type=design&node-id=3649%3A31264&mode=design&t=LpX0Wx80R6SXcYAl-1)

![Screenshot 2024-05-09 at 19 58 13](https://github.com/status-im/status-desktop/assets/97019400/0585a56f-6f78-4e74-8695-bd541688164e)

Details of the `User Story` and scenarios to cover [HERE](https://www.notion.so/Errors-on-pasting-dApp-URI-386ca2ccfc5d4d5082a8ed5f4f680868)

Add the following validation to the URL input:
- [x] Invalid url [#14590](https://github.com/status-im/status-desktop/pull/14590)
- [x] URL with emoji [#14590](https://github.com/status-im/status-desktop/pull/14590)
- [x] URL already used; implement `WCUriInput.wcUriAlreadyUsed` by checking the persistence [#15468](https://github.com/status-im/status-desktop/pull/15468)
- [x] Pairing URL expired; [#15468](https://github.com/status-im/status-desktop/pull/15468)
  - implement `WCUriInput.wcUriExpired` (there is no direct API but if expired might not get into the list); fallback: update DB and check the DB?
- [ ] Not supported network used [#15491](https://github.com/status-im/status-desktop/pull/15491)
- [ ] Handle possible SDK errors in approval of the initial connection that is required to transition to `ConnectDAppModal`. [#15491](https://github.com/status-im/status-desktop/pull/15491) 
  - now we disable the `Done` button and don't show anything (e.g. "something went wrong, try again").
- [ ] Handle case of no error on pairing but also no `session_request` in a reasonable time [#15491](https://github.com/status-im/status-desktop/pull/15491)
