### ISSUE TITLE
[EPIC - Swap UI] UI components needed for covering swap flows

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14786]
### Description

[Design](https://www.figma.com/file/TS0eQX9dAZXqZtELiwKIoK/Swap?type=design&mode=design&t=JHqahc5HB25yX7uV-0)

Here there are listed the **UI components** needed for covering **swap** flows:

- [x] #14779
- [x] #14780
- [x] #14781
- [x] #14782
- [x] #14783
- [x] #14784
- [x] #14792
- [x] #14785
- [x] https://github.com/status-im/status-desktop/issues/14499
- [x] https://github.com/status-im/status-desktop/issues/15442
- [x] https://github.com/status-im/status-desktop/issues/15443

Issues:
- [x] #15275
- [x] #15276
- [ ] #15277
- [x] #15278 
- [ ] https://github.com/status-im/status-desktop/issues/15313
- [x] #15412
- [x] https://github.com/status-im/status-desktop/issues/15445
