### ISSUE TITLE
Integrate the new cost (#15190) and time (#15191) APIs with the UX

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#15192]
Build on top of #15190 and #15191 to provide the following user stories:

- [ ]  the user should see the transaction params in a human-readable format (where possible) [#15645](https://github.com/status-im/status-desktop/pull/15645)
    - number fields (amount/gas/etc.) should be converted from hex to human-readable numbers [#15645](https://github.com/status-im/status-desktop/pull/15645)
- [x]  the user should see the max fees for this transaction [#15552](https://github.com/status-im/status-desktop/pull/15552)
- [x]  the user shouldn’t be able to proceed if they don’t have enough assets to pay the gas fees [#15643](https://github.com/status-im/status-desktop/pull/15643)
    - [x]  the user should see a warning [#15643](https://github.com/status-im/status-desktop/pull/15643)
- [ ]  the user shouldn’t be able to proceed if they don’t have enough assets to complete the transaction [#15645](https://github.com/status-im/status-desktop/pull/15645)
    - [ ]  the user should see a warning [#15645](https://github.com/status-im/status-desktop/pull/15645)
- [x] https://github.com/status-im/status-desktop/pull/15508
