### ISSUE TITLE
[UI - Wallet Stability]  Ensure / review all the entry points for `Send`

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#15217]
Ensure all the **User Stories** and **details** defined in here are covered and working as expected:
- https://www.notion.so/Launch-Send-Tokens-flow-80100fdeed394af5bbf496f8670ed94a

**Comment by noeliaSD** [comment]
It would make sense to work on it together with https://github.com/status-im/status-desktop/issues/15215

**Comment by noeliaSD** [comment]
Ensure we are also covering this use case https://github.com/status-im/status-desktop/issues/14732 here. It's part of one of the user stories, but I link the task, as a reminder!

**Comment by alexjba** [comment]
### TO-DO Send Modal

NOTE: General rules (TBD) 
- Preselecting the assets or collectible in the send modal:
      1. When send modal is opened in the context of an asset or collectible (context menu, token details)
- Preselecting the account:
      1. When the send modal is opened in the account context, that account is preselected
      2. When the send modal is opened in the context of all accounts and owned asset or collectible, the first account with positive balance is selected from the account list sorted by wallet position
      3. When the send modal is opened in the context of all accounts the first account in the sorted account list is preselected

- [ ] Add footer button when `all accounts` is selected. This should cover all tabs (Token details, activity, Collectibles, Assets)
- [ ] (Maybe! TBD) - Don't show the send button in context menu for the collectibles not owned in any user account (https://www.notion.so/From-Main-Wallet-View-Context-menu-ff2c779b113e4243b5364c465188ea3a?pvs=4#bef0d8e5e434444e9b8ffaf53c5b86a8)
- [ ] When opening the send modal from assets context menu we should preselect the first account holding a balance > 0
- [ ] (TBD) When opening the send modal from collectibles context menu we should preselect the first account that holds a balance > 0
- [ ] Disable `Send` context menu for assets and accounts not owned by the user or not transferable.
- [ ] (TBD) Preselect the account and token when send modal is opened from Token details view.
- [ ] Add `Repeat transaction` context menu button on `Sent` transactions in the activity view. Clicking this opens the send modal with all the data preselected to repeat the transaction (from, to, amount, token)
- [ ] (TBD: Can we preselect the amount?) Preselect the account, token and amount for the owner token in the `Transfer ownership` flow

**Comment by alexjba** [comment]
#### CHORES:

- [] Fix crash when activating the send modal from `All accounts` footer option

**Comment by alexjba** [comment]
Notes for QA team: Please test/add squish tests for the default account selection in `Send`, `Bridge`, `Swap`, `Receive` and `DApp` when we have a `watch-only` account defined as the first account in the account order settings.
Currently the default account selection is broken in this flow. Will be fixed as part of this task.

cc @anastasiyaig

**Comment by anastasiyaig** [comment]
@Valentina1133 pls work on that as next item

**Comment by alexjba** [comment]
For reference, this is from the latest master:

https://github.com/user-attachments/assets/6320f27e-109b-487e-b426-2e0b72d1adba

@Valentina1133

**Comment by Valentina1133** [comment]
> For reference, this is from the latest master:
> 
>  Screen.Recording.2024-07-17.at.11.38.28.mov 
> 
> @Valentina1133

Ok. Got it. Will be covered, created a task for that
