### ISSUE TITLE
[UI - Wallet Stability] Refactor `SendModal` to use the new / reworked components

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#15215]
It should contain:
- [x] New `AccountsSelector`- support for collectibles #15121
- [x] Integrate new `TokensSelector` to the `SendModal` #15512
- [x] New `StatusAmountIputPanel` built on #15207
- [x] New combo for selecting tokens build from #14716 and #15121
- [x] New component to manage selected recipiends built on #15208
- [x] The renamed `TransactionModalFooter` reworked on #15212
- [ ] The renamed component `RouterPanel` reworked on #15209
- [ ] No references to **bridge** feature
- [ ] **No** references to **global network** selections (only references to _testnet_)

Some pseudo-code:

```
StatusDialog {
    id: root

    property var selectedAccount
    property var selectedToken
    property var selectedAmount
    property var selectedReceiver
    property var bestRoutes

    property models needed

    header: AccountSelector { ... }

    ColumnLayout {
        RowLayout {
            Send Text
            +
            Holdings selector
            +
            Max button component
        }
        RowLayout {
           StatusAmountInputPanel 1 (send)
           StatusAmountInputPanel 2 (receive)
        }

        Loader {
               ReceipientsSelector OR RouterPanel
        }
    }

    footer: TransactionModalFooter { ... }
}

```

It should implement the new design flow defined in [here](https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?m=auto&node-id=23970-465372&t=VyetOnjSegfO0pec-1):

![Screenshot 2024-06-17 at 16 44 06](https://github.com/status-im/status-desktop/assets/97019400/808350d8-8efd-408f-af38-26564ef74e8b)

**Comment by noeliaSD** [comment]
First it is needed to work on the subtasks mentioned on the description

**Comment by noeliaSD** [comment]
When working on this task, please ensure we are covering the following fix: https://github.com/status-im/status-desktop/issues/14923

If necessary, create specific `qml test` for the bug so we have coverage there!

**Comment by micieslak** [comment]
The work will be continued in https://github.com/status-im/status-desktop/issues/15688
