### ISSUE TITLE
Support archive protocol when transferring control node to new device/account

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#15235]
### Description

Transferring control node to another device/account will most likely break archive protocol.

Issue in detail, by @0x-r4bbit:
> I don't think I've tested this scenario back then because when this feature was build there was no transfer of control node expected. Even transferring the private key of the community (which was the only option back then) was a scenario that simply wasn't really suitable for this archive protocol.
> 
> Here's what I would expected to happen:
> 
> 1. Assuming the new control node does not have all the previous archive data, it will likely query historic messages from store nodes and create new archives and publish magnetlinks as usual
> 2. Other nodes will read the magnetlink and try to figure out which archives of the provided torrent they need to download (last time I worked on this, they'd download all archives they don't yet have by checking the archive IDs)
> 3. The problem here now is that, when the new control node creates new archives and doesn't have any previous data, it will have different byte offsets in the archive index. In other words, the first archive it creates will start at index 0 - length of archive. The second archive starts at offset "length of archive 1" and so on and so forth. Nodes that have consumed a torrent from a previous control node that already generated and published archives in the past, will then still download the archives of the hashes they don't yet have, but they might override the bytes in the BLOB of previous archives that occupied the same location.
> 
> So I'd assume this to potentially break archives.

Possible solutions, by @0x-r4bbit:

> 1. Always ensure that the new control node has downloaded all previous torrent data and an up-to-date message archive index, such that the new archives will only be appended to the blob.
> 2. If ensuring previous torrent isn't feasible (for whatever reason), then I think the control node has to at least create an empty blob with the same byte size as the current archive blob, create a torrent from that and append new archives there
> 
> Option 2) ensures that new archive data will not override existing torrent data. But the result is still an incomplete torrent, which kind of defeats the purpose of the protocol.

### Tasks
- [ ] Test scenario in isolation to confirm its characteristics
- [ ] Come up with solution proposal, discuss it with @status-im/desktop-core-team & @0x-r4bbit
- [ ] Implement approved solution
