### ISSUE TITLE
EPIC: Simplified Send Transaction

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#16696]
### Description

As a first step in stabilising and having a bug free send, the team has decided to go ahead with single network send as a version 1.

This epic covers all the changes that need to be done in send as finalised by the team.

**Designs:** https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=25182-169274&t=Ech2sOd4zCGhGFzC-4
**User Stories:** https://www.notion.so/Making-transactions-Send-Bridge-Simplified-1128f96fb65c80d78d6ed0788776e98f?pvs=4

SubComponents Rework:
- [x] #16702
- [x] #16703
- [x] #16705
- [ ] https://github.com/status-im/status-desktop/issues/15709
- [x] #16706
- [x] #16707
- [x] #16708
- [x] #16918
- [x] #17180
- [ ] #16999

**Main Tasks:**
- [x] #16710
- [x] #17023
- [x] #16820
- [x] #16916
- [x] #16903
- [x] #16878
- [x] #16835
- [x] Using Max control
- [x] #16913
- [x] Fees calculation
- [x] #17060
- [x] #17000
- [x] Toasts
- [x] #16836
- [x] #16919

Miscellaneous TBD:
- [x] #17148
- [x] #17112
- [x] User AccountSelectorAdaptor defined here https://github.com/status-im/status-desktop/pull/16834
- [ ] Remove old SendModal
- [ ] Remove logic from nim code
- [ ] user new router formats only and remove the old ones
- [x] #17186
- [x] #17114
- [x] #17141
- [x] #17123
- [x] #17132
- [x] #17265
- [x] #17280
- [x] #17310

Additional:
- [ ] #17369

**Comment by Khushboo-dev-cpp** [comment]
> I left some comments in subtasks.
> 
> Moreover I noticed one big thing necessary to do along with the planned simplifications. It's consequence of design changes regarding scrolling:
> 
> ![Image](https://github.com/user-attachments/assets/538ad28e-67cf-43af-88ec-54991af679ad)
> 
> It means that top level layout of `SendModal` needs to be rethought and organised from scratch with that scrolling behavior in mind. Everything above the list should be put into ListView header probably.

@micieslak this behaviour only applies when screen size < 720 px. 

But your suggestion for moving everything above the list to listview header makes sense. We could play with sticky property based on screen height.

**Comment by virginiabalducci** [comment]
Hi @Khushboo-dev-cpp 

I've started testing and I'll post issues or questions to validate whether they are issues. I'll edit this comment as I go

### Issue 1
There is a padding or margin issue in the 'Assets' tab of the 'Select token' drop-down

![Image](https://github.com/user-attachments/assets/3f3588e8-f2cc-4d46-93de-a2433c886c02)

### Issue 2
The Max amount does not match the total amount of tokens. Is this intentional because it includes the gas fee? If so, there is no indication that this is happening.

https://github.com/user-attachments/assets/ef932e82-27ce-4ba2-b650-0585c4d97b12

**Comment by virginiabalducci** [comment]
### Issue 14

Send a collectible flow - Sign transaction modal: Rejecting or signing the transaction will lead the user to a blank screen with an invalid or incorrect collectible. 
This happens with ERC-721 and ERC-1155 tokens

https://github.com/user-attachments/assets/9b4dd9e2-2952-4d16-bc6c-21d6ef2fe292

![Image](https://github.com/user-attachments/assets/b4b7b98a-2ddd-4d80-8668-980c1981f5d6)

https://github.com/user-attachments/assets/a59e6928-20e0-4c7d-9058-2fe4c7803d58

**Comment by virginiabalducci** [comment]
Related issue reported here https://github.com/status-im/status-desktop/issues/17291

**Comment by virginiabalducci** [comment]
###Issue 15
The background icon of a saved account and the user's account are displayed with a black background on the Sign modal. This is reproducible on the latest master, on both light and dark themes.

<details><summary>Details</summary>
<p>

https://github.com/user-attachments/assets/ab443da6-1b58-4160-b5f7-15c702aee1e4

<img width="613" alt="Image" src="https://github.com/user-attachments/assets/4cec0ea2-0e49-4351-bd3f-5ba2673c3534" />

<img width="599" alt="Image" src="https://github.com/user-attachments/assets/24214b47-cdf3-4359-b9a5-0709db056cad" />

</p>
</details>

**Comment by Khushboo-dev-cpp** [comment]
@anastasiyaig @virginiabalducci can we close this Epic as it is completed in 2.33? in case of any pending issues maybe we can add those separately?
