### ISSUE TITLE
Replace modals used in community view with `StatusModal`

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#2881]
This is an epic that consists of the following subtasks:

- [x] https://github.com/status-im/status-desktop/issues/2882
- [x] https://github.com/status-im/status-desktop/issues/2883
- [x] https://github.com/status-im/status-desktop/issues/2884
- [x] https://github.com/status-im/status-desktop/issues/2885
- [x] https://github.com/status-im/status-desktop/issues/2886
- [x] https://github.com/status-im/status-desktop/issues/2887
- [x] https://github.com/status-im/status-desktop/issues/2888
- [x] https://github.com/status-im/status-desktop/issues/2889
- [x] https://github.com/status-im/status-desktop/issues/2890
- [x] https://github.com/status-im/status-desktop/issues/2891
- [x] https://github.com/status-im/status-desktop/issues/2892
- [x] https://github.com/status-im/status-desktop/issues/2893
- [x] https://github.com/status-im/status-desktop/issues/2894

**Comment by PascalPrecht** [comment]
There's an ongoing effort for this here: https://github.com/status-im/status-desktop/pull/2867

**Comment by PascalPrecht** [comment]
Closing this as done
