### ISSUE TITLE
Language & Currency settings screen

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4917]
needs https://github.com/status-im/StatusQ/issues/563

### Description

https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=701%3A74776

![Screen Shot 2022-02-26 at 1 13 18 PM](https://user-images.githubusercontent.com/176720/155854451-a1884a42-d208-4571-bee7-725d6ce00208.png)

* [x] Rename setting section "Language" to  "Language & Currency". -- Subtask [5384](https://github.com/status-im/status-desktop/issues/5384)

* [x] Replace Language picker with the Select Component -- Subtask [5384](https://github.com/status-im/status-desktop/issues/5384)

![Screen Shot 2022-02-26 at 1 13 39 PM](https://user-images.githubusercontent.com/176720/155854463-891d39a9-a8c2-4726-9990-9cabda60aab4.png)

![Screen Shot 2022-02-26 at 1 13 53 PM](https://user-images.githubusercontent.com/176720/155854468-0b9fdb0a-06fb-48b7-96ad-9e9d18b5a053.png)

* [x] Add Display Currency Picker with the Select Component -- Subtask [5385](https://github.com/status-im/status-desktop/issues/5385)

* [x] Make wallet and any currency related UI code use chosen Display Currency -- Subtask [5385](https://github.com/status-im/status-desktop/issues/5385)

* [x] Add Date & Time Format and make relevant UI code use the chosen Format -- Subtask [5386](https://github.com/status-im/status-desktop/issues/5386)
