### ISSUE TITLE
QR Code Scan

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5070]
### Description

https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=3311%3A177518

### Acceptance Criteria

* [ ] User can request camera access to OS
* [ ] User can choose camera if multiple are available
* [ ] If QR code cannot be read it should display an error message
* [ ] If QR code is read succefully, then should show success screen then add value to originating input
* [ ] The QR code is triggered through the icon on the left bar

![unknown](https://user-images.githubusercontent.com/176720/158847362-11722e05-ac53-440e-aa2d-17ee4540b1c8.png)

**Comment by iurimatias** [comment]
moving to 0.13 because this has been put there as part of the planned features. but we need to review it as it has less priority vs other tasks (like community permissions and performance)

**Comment by iurimatias** [comment]
descoped
