### ISSUE TITLE
Community Banner

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5118]
### Description

figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=3132%3A383870

Add support to upload a banner for a community.

### Subtasks

- [x] `StatusQ` generic crop editor - [PR #615](https://github.com/status-im/StatusQ/pull/615) (merged)
- [x] #5401 (merged)
- [x] #5402 (merged)
- [x] #5403 (merged)
- [x] #5405 (merged)
- [x] #5850 (duplicate)
- [ ] #5404 (in testing)

### Acceptance Criteria

* [ ] creating a community dialogue should support choosing an image for the community banner
  * This needs small changes and depends on the work done with the refactoring of the new Create Community dialogue: https://github.com/status-im/status-desktop/pull/5884
* [x] editing a community should support changing the image for the community banner
