### ISSUE TITLE
Handle synchronization messages

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#5201]
The following attributes are not being handled in `messages.new` signal:
https://github.com/status-im/status-go/blob/develop/protocol/messenger_response.go#L68-L79
- `mailservers`
- `bookmarks`
- `clearedHistories` -  indicates which channels history must be removed
- `communitiesSettings`
- `currentStatus` -  If the user changes the status in another device, we should change the status of the current device
- `settings` -  We must verify which settings are being sync. Probably we should not update all the settings

A messages.new signal will contain these when accounts are being synced. Desktop UI and nim backend should be updated to reflect any change received

**Subtasks**

- [x] Handle sync bookmarks (https://github.com/status-im/status-desktop/pull/6043)
  - [x] Ensure bookmarks are synced in the first place (https://github.com/status-im/status-go/issues/2704)
  - [x] Garbage collect bookmarks marked as removed (https://github.com/status-im/status-go/issues/2705, https://github.com/status-im/status-go/pull/2711)
- [x] Handle sync cleared histories
  - [x] Ensure clear history is synced in real-time (https://github.com/status-im/status-go/issues/2714)
  - [x] Handle sync clear history messages in desktop (https://github.com/status-im/status-desktop/pull/6076)
- [x] Handle sync community settings
- [x] Handle sync current status (https://github.com/status-im/status-desktop/pull/6085)
- [x] Handle sync settings
  - [x] Handling `currency`  (https://github.com/status-im/status-desktop/pull/6111)
  - [x] Handling `show-profile-pictures-to` (https://github.com/status-im/status-desktop/pull/6096) 
  - [x] Handling `profile-pictures-visibility` (https://github.com/status-im/status-desktop/pull/6096)

**Comment by PascalPrecht** [comment]
PR to sync `CommunitySettings` is here: https://github.com/status-im/status-go/pull/2701

Investigating the other fields now

**Comment by PascalPrecht** [comment]
Sync communities settings are handled here: https://github.com/status-im/status-desktop/pull/5993

**Comment by PascalPrecht** [comment]
Bookmarks are not synced automatically atm, but only when devices are explicitly synced.
Will iron that out next.

**Comment by PascalPrecht** [comment]
Bookmark syncing is now addressed in 

- https://github.com/status-im/status-go/issues/2704
- https://github.com/status-im/status-desktop/pull/6043

Looking into garbage collecting soft deleted bookmarks next

**Comment by PascalPrecht** [comment]
Turns out clearing histories is not synced in real-time either. Working on that next https://github.com/status-im/status-go/issues/2714

**Comment by PascalPrecht** [comment]
Here's a PR that handles sync clear history messages in desktop: https://github.com/status-im/status-desktop/pull/6076 This should already work when syncing devices. It will also work in real-time when the corresponding status-go PR lands.

**Comment by PascalPrecht** [comment]
Working on handling user status updates next. Turns out those are not broadcasted at the moment, which makes it hard to get them synced in realtime.

**Comment by John-44** [comment]
@PascalPrecht the list looks good, the only thing I have a question about is "messages from contacts only".  With mutual contacts, only contacts will be able to send the user 1on1 messages, so this statement implies syncing *all* 1on1 messages.  This is good I think.  However in ad-hoc group chats there might might be some participants in an ad-hoc group chat who are not a mutual contact of the user.  So instead of saying "messages from contacts only", we might want to consider either saying "all 1on1 messages" *OR* "all 1on1 messages and all ad-hoc group chat messages".  If we say the latter, then the statement "messages from contacts only" would be incorrect because some messages in an ad-hoc group chat might come from people.

Other than clarifying the point above, all other items are good to include in the user profile data that is synced.  There is also a bunch of additional stuff that needs to be synced that isn't included in this list, but I assume that extending the scope of settings that are synced would be additional tasks for somebody to pickup in the future.

**Comment by John-44** [comment]
> Thanks for the feedback @John-44 The list above if the names of the **settings** that are being synced. So I assume "messages from contacts only" is the setting that dictates whether one can receive messages from non-contacts (this is probably an artifact from times before we had mutual contacts).
> 
> So this is not about syncing messages, but settings (or whatever is store in "settings")

@PascalPrecht ahh that makes more sense, as I thought we weren’t syncing msg content itself. Thx for the explanation :-)

**Comment by PascalPrecht** [comment]
There's an issue with updating the currency value after syncing in the view. Filed an issue here #6092 and will let this sit for now until resolved.

**Comment by PascalPrecht** [comment]
`show-profile-pictures-to` setting is handled here https://github.com/status-im/status-desktop/pull/6096

**Comment by PascalPrecht** [comment]
Currency settings are handled here: https://github.com/status-im/status-desktop/pull/6111 although, as mentioned in #6092 there's an issue with it not updating the view.

**Comment by PascalPrecht** [comment]
#6111 has landed, therefore this issue can be closed
