### ISSUE TITLE
Complete work for derivation path

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#5453]
- [x] [#5655](https://github.com/status-im/status-desktop/issues/5655): show appropriate activity in derived addresses list (has activity/ no activity)
- [x] infinite number of pages in derived addresses list - as disscused with carl we will show first 100 for the rest the user can entire path and see the address he wishes . Closing this
- [x] move derivation path list once confirmed by carl to status_go - again there will be no list only one item. need to adapt to that will do it add with add custom derivation path flow
- [x] [#5539](https://github.com/status-im/status-desktop/issues/5539): greying out already imported/derived addresses in address list and also choosing next available as default one
- [x] #5700 : add custom derivation path - one only by default and then switch to custom one. let user add the whole path and show corresponding address as well
- [x] #5699 : Private key flow and show address to user
- [x] adapt similar view for settings - can be handled separately as design isnt ready. https://github.com/status-im/status-desktop/issues/5725

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=4205%3A176023

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)
