### ISSUE TITLE
Refactor Epic

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5744]
### Description

Backend:
- [ ] Make all calls to backend async (previously issue 5507)
- [ ] Move new version checking code to status-go (previously issue 4884)
- [ ] refactor: create status-go signals for activity center (previously issue 5054)
- [ ] refactor: Community Service community entity methods (previously issue 5057)
- [ ] refactor: new getWallets api #5050
- [ ] [getChats] remove old chats object from chat service (previously issue 5185)
- [ ] refactor: simplify gif api (previously issue 5056)
- [ ] [getChats] refactor chats models to only be one layer, with categories being sections (previously issue 5286)
- [ ] new getWallets api (previous issue [here](https://github.com/status-im/status-desktop/issues/5050))

QML:
- [ ] Chat: Usage of stores needs to be stream lined (previously issue 4823)
- [ ] Improve StatusEmojiPopup speed and add loading indicator (previously issue 4959)
- [ ] Refactor Input to StatusInput in AppLayouts/Onbording/popups/GenKeyModal.qml and update validator (previously issue 5299)

Other:
- [ ] Create needed enums for date format and time format and replace boolean properties (when C++ project is ready and exposing enums is not costly) (previously issue 5635)
- [ ] Attach transaction to wallet account (previously issue 5206)
- [ ] Move Language and Currency stores logic to backend (initialization to nim, data to status-go) (previously issue 5498)
