### ISSUE TITLE
C++ Epic

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5745]
- [x] https://github.com/status-im/status-desktop/issues/5676
- [x] https://github.com/status-im/status-desktop/issues/5681
- [x] #6028
- [x] #6321
- [ ] #6307
- [x] #5998 (WIP)
- [x] https://github.com/status-im/status-desktop/issues/5690
- [ ] https://github.com/status-im/status-desktop/issues/5689
- [ ] add gtest to cpp app (previously issue 4853)
- [ ] add c++ builds to the CI (previously issue 4844)
- [ ] clarify `status-go` API io requirements for strings, paths ...
- [ ] Integrate codechecker with Jenkins (previously issue 4640)
- [ ] add code formatter (previously issue 4431)
- [ ] C++ - Logging support with QT/QML integration (previously issue 5692)
- [ ] C++ - CI: add clang-tidy and clang-format checks (previously issue 5693)
- [ ] #7836
- [ ] C++ - Integrate dependency injection (previously issue 5696)
- [ ] C++ - Finalize CI, Windows and MacOS platforms build and Packaging for all
- [ ] Setup Conan as a third-party Package Manager (previously issue 5698)
