### ISSUE TITLE
Packaging & Build Epic

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5747]
Packaging
- [ ] .deb deployment (previously 3601)
- [ ] Package to UWP (previously 1684)
- [ ] Build Flatpak release (previously 8266)

Improvement
- [ ] Review all packaged build metadata for all platforms (previously 915)
- [ ] For dev builds the QtWebEngine directory should be inside the data directory. (previously 1141)
- [ ] Check Windows packaged build's resistance to tampering (previously 914)

Other
- [ ] Clean up root folder (previously 3367)
- [x] #5983

**Comment by du64** [comment]
It would be awesome if the desktop app could look like a Gnome app on Gnome, and a Windows app on Windows.

**Comment by iurimatias** [comment]
closing for now but this part of the overall requirements for the desktop app store story
