### ISSUE TITLE
Group chat epic

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#5861]
Implementation tasks needed to align with [group chat specs
](https://github.com/status-im/feature-specs/pull/75)

#### status-desktop
- [x] https://github.com/status-im/status-desktop/pull/5821
- [x] add members management ([details](https://github.com/status-im/feature-specs/pull/75#discussion_r879593148))
- [x] add group appearance editing capabilities ([details](https://github.com/status-im/feature-specs/blob/79e9e0eda171f0d7a8acd5cbaff34723ebf8d034/content/raw/chat/group_chat.md#group-appearance))
- [x] #5982
- [x] #7154
- [x] #7155

##### bugs
- [x] https://github.com/status-im/status-desktop/issues/7146

#### status-go
- [x] https://github.com/status-im/status-go/pull/2684
- [ ] https://github.com/status-im/status-go/issues/2683
- [x] https://github.com/status-im/status-go/issues/2825
- [x] https://github.com/status-im/status-go/issues/2823
- [x] https://github.com/status-im/status-go/issues/2824
