### ISSUE TITLE
Import tool

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6081]
Tool to import chats from discord

**UPDATE BY @PascalPrecht**:
The following things need to be done for this:

**UI Changes**

- [x] Add dialog to create a community or import a discord community
- [x] Update create community dialog title to "Import community from discord into Status"
- [x] Update "create community" button to "import from Discord" button
- [x] Introduce new dialog screen to manage import
  - [x] Add file selector and button so users can choose files to import
  - [x] List chosen files and allow users to remove them again
  - [x] Add "Import" button, enabled when files were chosen
  - [x] Add form control to let users specify date from which to import messages
    - [x] Also add "All history" checkbox which is checked by default
  - [x] List available categories and channels retrieved from imported file
    - [x] Allow users to check/uncheck which categories/channels they want to import   
  - [x] Add "Finalize import" button
  -  [x] Ensure Desktop actually renders newly imported messages
- [x] https://github.com/status-im/status-desktop/issues/6677
- [x] https://github.com/status-im/status-desktop/issues/6678
- [x] https://github.com/status-im/status-desktop/issues/6679
- [x] https://github.com/status-im/status-desktop/issues/6680
- [ ] https://github.com/status-im/status-desktop/issues/6681
- [x] https://github.com/status-im/status-desktop/issues/6683
- [x] https://github.com/status-im/status-desktop/issues/6684
- [x] https://github.com/status-im/status-desktop/issues/6685
- [x] https://github.com/status-im/status-desktop/issues/6686
- [x] https://github.com/status-im/status-desktop/issues/6687
- [x] https://github.com/status-im/status-desktop/issues/6689
- [x] https://github.com/status-im/status-desktop/issues/6691
- [ ] https://github.com/status-im/status-desktop/issues/6692
- [x] https://github.com/status-im/status-desktop/issues/6690
- [x] https://github.com/status-im/status-desktop/issues/6693
- [x] https://github.com/status-im/status-desktop/issues/6717
- [x] https://github.com/status-im/status-desktop/issues/6716
- [x] https://github.com/status-im/status-desktop/issues/6788
- [x] https://github.com/status-im/status-desktop/issues/6814
- [x] https://github.com/status-im/status-desktop/issues/6841
- [x] https://github.com/status-im/status-desktop/issues/6923
- [x] https://github.com/status-im/status-desktop/issues/6933
- [x] https://github.com/status-im/status-desktop/issues/6934
- [x] https://github.com/status-im/status-desktop/issues/6948
- [x] https://github.com/status-im/status-desktop/issues/7198
 
**Logic/Functionality**

- [x] Read and parse json of chosen files to import (
- [x] Determine oldest message date
- [x] Determine available categories and channels
- [x] Add API/response to get categories/channels list
- https://github.com/status-im/status-go/pull/2752
- [x] Create empty community with desired channels and categories
- [x] https://github.com/status-im/status-go/issues/2758
- [x] https://github.com/status-im/status-go/issues/2759
- [x] https://github.com/status-im/status-go/pull/2767
- [x] https://github.com/status-im/status-go/pull/2768
- [x] https://github.com/status-im/status-go/issues/2760
- [x] Introduce new import related signals
- [x] Ensure different message types are handled properly
  - [x] Default
  - [x] Reply
  - [x] https://github.com/status-im/status-desktop/issues/6682
- [x] Make import API async
- [ ] explore multi-threaded import (for better progress updates
- [x] Create history archives from imported messages

**Comment by PascalPrecht** [comment]
Closing this as done.
