### ISSUE TITLE
Mutual Contact Requests Epic

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6114]
figma: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1125%3A139397

- [ ] https://github.com/status-im/status-desktop/issues/4783
- [ ] https://github.com/status-im/status-desktop/issues/4784
- [ ] https://github.com/status-im/status-desktop/issues/5932
- [ ] https://github.com/status-im/status-desktop/issues/6113
- [ ] In Profile menu show options for "Respond to Contact Request", "Contact Request Pending"
- [ ] In Profile menu show options for Identity Verification

**Comment by elina2015** [comment]
Waiting for the finishing the implementation
