### ISSUE TITLE
Browser Epic

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6775]
### Description

- [ ] Human Readable data display when signing using eth_signTypedData_v3 (see old issue [here](https://github.com/status-im/status-desktop/issues/3355)
- [ ] Playing media in browser doesn't work (see old issue [here](https://github.com/status-im/status-desktop/issues/4326))
- [ ] workaround needed for dapps that don't support normal web3 providers (see old issue [here](https://github.com/status-im/status-desktop/issues/3323) and [here](https://github.com/status-im/status-desktop/issues/6006))
- [ ] Chain id does not match with signing typed message on ropsten in simpledapp (see old issue [here](https://github.com/status-im/status-desktop/issues/6610))

**Comment by iurimatias** [comment]
closing for now, but generally it's still part of the long term roadmap TBD
