### ISSUE TITLE
Chat Send/Receive Transaction Epic

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6778]
### Description

The Chat Send/Receive Transaction is currently deprioritized but it will need some love once it's a priority again

issues:
- [ ] chat send/request transaction widget doesnt update after transaction is sent in 1 on 1 chat (previous issue [here](https://github.com/status-im/status-desktop/issues/5478))
- [ ] Nothing happens when request a transaction in 1-1 chat (previous issue [here](https://github.com/status-im/status-desktop/issues/6265))
- [ ] Transaction bubbles are not present in chat (previous issue [here](https://github.com/status-im/status-desktop/issues/6429))
- [ ] NaN instead of balance when transacting in chat (previous issue [here](https://github.com/status-im/status-desktop/issues/6430))
- [ ] The error message 'Error sending the transaction' doesn't look good (previous issue [here](https://github.com/status-im/status-desktop/issues/6557))
- [ ] App is crashing when sending a transaction request in chat (previous issue [here](https://github.com/status-im/status-desktop/issues/6617))
