### ISSUE TITLE
Review & fix/improve activity center

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7070]
### Description

Review currently Activity center functionality according to designs and specs ( see https://github.com/status-im/feature-specs/pull/30/files )
Fix any issues that might arise, preferably with accompanying squish tests

Child issues:
- [x] https://github.com/status-im/status-desktop/issues/7161
- [x] https://github.com/status-im/status-desktop/issues/7338
- [x] https://github.com/status-im/status-desktop/issues/7016
- [x] https://github.com/status-im/status-desktop/issues/7273
- [x] https://github.com/status-im/status-desktop/issues/7361
- [x] https://github.com/status-im/status-desktop/issues/7274
- [x] https://github.com/status-im/status-desktop/issues/7275
- [x] https://github.com/status-im/status-desktop/issues/7276
- [x] https://github.com/status-im/status-desktop/issues/7277
- [x] https://github.com/status-im/status-desktop/issues/7373
- [x] https://github.com/status-im/status-desktop/issues/7507
- [x] https://github.com/status-im/status-desktop/issues/5639
- [x] https://github.com/status-im/status-desktop/issues/7363
- [x] https://github.com/status-im/status-desktop/issues/7365
- [x] https://github.com/status-im/status-desktop/issues/7489
- [x] https://github.com/status-im/status-desktop/issues/7492
- [x] https://github.com/status-im/status-desktop/issues/7497
- [x] https://github.com/status-im/status-desktop/issues/7499
- [x] https://github.com/status-im/status-desktop/issues/7475
- [x] https://github.com/status-im/status-desktop/issues/7529
- [x] #7536
- [x] #7654
- [x] https://github.com/status-im/status-desktop/issues/7635
- [x] #7655
- [x] https://github.com/status-im/status-desktop/issues/7656
- [x] https://github.com/status-im/status-desktop/issues/7674
- [x] #7952
- [x] #7980
- [x] #8285
- [x] #8387
- [x] #8388
- [x] #8434
- [x] #8499 
- [x]  #8586
- [x] #8834

**Comment by MishkaRogachev** [comment]
Table: https://docs.google.com/spreadsheets/d/1tZn24TRPHiROxz5YaLzAxZWneM2HP6MI0b1VkiPw-IA/edit?usp=sharing

**Comment by MishkaRogachev** [comment]
Figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1854%3A298745

**Comment by MishkaRogachev** [comment]
Notifications logic: https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=639%3A21924

**Comment by anastasiyaig** [comment]
@iurimatias @jrainville it is scheduled for 0.9.0 - is it still doable?
