### ISSUE TITLE
[StatusQ] Move `StatusChatInput` to StatusQ

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7584]
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1%3A11

---
Updated description by @PascalPrecht 

---

This component lives currently [here](https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusChatInput.qml) and consists of a bunch of other components that compose this one.

Essentially this means we need to:

- [ ] Move `StatusChatInput` to StatusQ and all of its composing components:
  - [ ] [`StatusChatInputImageArea`](https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusChatInputImageArea.qml) (#211)
  - [ ] [`StatusChatInputReplyArea`](https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusChatInputReplyArea.qml) (#210)
  - [ ] [`StatusChatInputTextFormationAction`](https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusChatInputTextFormationAction.qml) (probably needs status-im/status-desktop#7588)
  - [ ] [`StatusChatCommandButton`](https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusChatCommandButton.qml)
  - [ ] [`StatusChatCommandPopup`](https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusChatCommandsPopup.qml) (#208)
- [ ] make sure that the (moved) components  are decoupled from `chatsModel` and provide hooks and APIs for consumers to configure the conponent and interact with it
- [ ] take a look at how image drag'n'drop is integrated into that component can think how that can live in StatusQ (if it has to)
- [ ] move all `StickerMarket*` related components to StatusQ (#205)
- [ ] move emoji popup to StatusQ

... and probably some more things (items will be added as they occur).
