### ISSUE TITLE
[Wallet] Add loading screen when loading price

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#7661]
There is currently a delay when displaying the data, we need to add a loader

Design specifications for the wallet part: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=9476%3A104890&t=0dmh4P2fNePbMgAH-0

Design issue https://www.notion.so/Desktop-Wallet-Loading-states-required-efed2bbb7db64b7a8b7ae1f061fa1325

subdividing this task:

- [x] Create base animation needed for the loading state
- [x] Add support loading state for a text element
- [x] Add support for statuslistItem loading
- [x] Add losing state for left side accounts list
- [x] Add loading state for Assets list
- [x] Add loading state for history list
- [x] Add loading state for collectibles list
- [x] Add loading state for Assets Details
- [x] Add loading state for send modal and bridge UI

**Comment by stefandunca** [comment]
@John-44 postponing this issue until we have an answer from the design team on the question of the waiting state in this corner case when data is not yet fetched or processed.
Another question I posted in the design channel is if we expect to cache price history as for the balance history.

The behaviour I see on the Linux system is different than high-end Mac, the graph displaying was hanging for one or two seconds which might be a limitation from our plotting technology (Chart.js) to process the data on some low spec/drivers systems.

Here is the behaviour of graphing prices for a new account on an apple silicon MacBook with a good connection
https://user-images.githubusercontent.com/47554641/200853898-de639a45-6103-4bd1-ab09-a70c98f7bc34.mov

**Comment by benjthayer** [comment]
After discussing with @stefandunca the specific UI areas which require loading states are attached. If there are any additional loading states beyond those shown feel free to list them.

<img width="1396" alt="Asset-loading-01" src="https://user-images.githubusercontent.com/110033914/201949401-e5852dab-2996-43ee-9de0-0bcae7db35f6.png">
<img width="1396" alt="Asset-loading-02" src="https://user-images.githubusercontent.com/110033914/201949413-0901a332-0183-474b-9680-a1154291c100.png">
<img width="1396" alt="Asset-loading-03" src="https://user-images.githubusercontent.com/110033914/201949419-a833c159-f7f8-4988-a0fe-5d7bb4235678.png">

**Comment by benjthayer** [comment]
@stefandunca as promised, I've attached and linked to the new wallet loading states below.

You will notice a couple of modifications to the existing loading state asset which are detailed in the file - but feel free to comment on technical feasibility.

1) In the original design it looks as if the ghost/skeleton loading asset, as a rule, is intended to match the height of the item it is loading in. So if it is loading in a text area that is 22px in height, the loading asset would also be 22px in height - matching the bounding box of the text. There are instances in the wallet design where 2 text boxes are stacked with 0px padding - this means that there is no padding between their respective loading assets which looks pretty bad. I've included a solution in the designs to prevent this where we use/calculate the cap-height of the text to set the height of the loading asset. Do feel free to comment on technical feasibility :)

2) The original design also uses solid colours which performs fine on white UI backgrounds but is not as visible on areas of the design, like the left panel in wallet, where the background is not white. I've proposed a new gradient which looks exactly the same as the original loading asset when on white but, given it uses opacity, it retains visibility on non-white backgrounds.

I've put the new loading state designs in the Wallet v2 figma - linked below.
If there is anything missing or if you would like to chat anything through do let me know :)

<img width="592" alt="01-Loading-system" src="https://user-images.githubusercontent.com/110033914/204568950-c5bc6dd3-98d1-4ed0-9126-b0c97370533b.png">
<img width="1188" alt="02-WalletAssets-loading" src="https://user-images.githubusercontent.com/110033914/204568961-ce2fc700-87ce-47e6-afc0-53e6065ada08.png">
<img width="1227" alt="03-AssetData-loading" src="https://user-images.githubusercontent.com/110033914/204568967-bc913690-d694-476b-a3c4-8623c5335b97.png">

**Comment by alaibe** [comment]
https://vimeo.com/756364088

**Comment by stefandunca** [comment]
> @stefandunca as promised, I've attached and linked to the new wallet loading states below.

Thanks, @benjthayer for coming back with the designs

> 1. ... use/calculate the cap-height of the text to set the height of the loading asset. Do feel free to comment on technical feasibility :)

This is feasible. However, using cap-height needs more work so for the first iteration we might use ascent which is easily available then see if this is enough for us and iterate.

> 2. ... I've proposed a new gradient which looks exactly the same as the original loading asset when on white but, given it uses opacity, it retains visibility on non-white backgrounds.

Sounds like a good idea. Will follow with it in the implementation.

**Comment by Khushboo-dev-cpp** [comment]
@benjthayer @johannesmw 
I see we had implemented these loading states in desktop before 

https://user-images.githubusercontent.com/60327365/211514561-3b8bdda2-781d-4aeb-9873-fa2640cb6d36.mov

Please let me know if these are still needed. The condition not covered with current design is the "loading failed" in red.

**Comment by benjthayer** [comment]
Thanks @Khushboo-dev-cpp , I believe the new loading states we've been working on can replace the top grey `Incoming device` variant. 

@John-44 are you happy with retaining the red skeleton load variant for data that has failed to load (shown above).  A couple of possible enhancements I can see are to:
1) Use some copy in place of the data that was due to load in eg `Data failed to load` possibly with any relevant remediation advice eg `Restart app and try again` / `reload page and try again`
2) A co-presenting icon prefixed to the error text or in place of the circular asset - this could be a refresh icon to try and load the data again or a generic error icon?

**Comment by John-44** [comment]
@Khushboo-dev-cpp I suggest that @benjthayer discusses with @pedro-et to get a second opinion on the red loading state, and I'll be +1 on whatever @benjthayer says after having had this discussion with @pedro-et :-)

**Comment by anastasiyaig** [comment]
I think it should be moved to next milestone @alaibe

**Comment by Khushboo-dev-cpp** [comment]
@anastasiyaig why next milestone?

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp by the time i left the comment, this current task was scheduled for 0.9.0 so i assumed it should be moved to 0.10, where is appears now :)
