### ISSUE TITLE
status-go wrapper Epic

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7828]
### Description

Status-go wrapper
- As singleton if necessary
- Service abstraction layer
- If there is service logic, if should be moved to status-go
- Almost all calls trigger signals

Naming
- get* - returns data sync (except existing calls that trigger signals)
- fetch* - always trigger a signal
- Any other send is async

- [ ] https://github.com/status-im/status-desktop/issues/7825
- [ ] https://github.com/status-im/status-desktop/issues/7826
- [ ] https://github.com/status-im/status-desktop/issues/7827
