### ISSUE TITLE
Deep Links Epic

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7840]
### Description

Spec: https://github.com/status-im/specs/blob/feature/url-shema/docs/draft/17-url-scheme.md

Deep links required for MVP:
- [x] User Profile
  - [x] https://github.com/status-im/status-desktop/issues/6651 
- [x] Community
  - [x] https://github.com/status-im/status-desktop/issues/7892
- [x] Community Channel
- [x] ~~Group Chat ❓ probably not feasible for MVP~~. removed from the scope

Post MVP links ❗ :
- [x] Browser - works correctly from both internal and external link
- [ ] Post in channel
- [ ] Post in group

No needed links:
- [x] Private Chat ❌ - not needed
  - [x] https://github.com/status-im/status-desktop/issues/7704 
- [x] Public Chat  ❌ - not needed
- [x] Community Requests  ❌ - not needed

related issues:
- [x] https://github.com/status-im/status-desktop/issues/6612
- [x] update feature specs
- [x] https://github.com/status-im/status-desktop/issues/6302
- [x] test deep links on Windows - Windows tested by Elina
- [x] https://github.com/status-im/status-desktop/issues/7988
- [x] https://github.com/status-im/status-desktop/issues/8001
- [x] https://github.com/status-im/status-desktop/issues/6650
- [x] https://github.com/status-im/status-desktop/issues/8070
- [ ] https://github.com/status-im/status-desktop/issues/8027
- [ ] https://github.com/status-im/status-desktop/issues/7957 -❗ feasible when new website is implemented
