### ISSUE TITLE
Community Portal Epic

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7841]
### Description

The portal needs to be taken to the finish line somewhat. Including using featured communities, using mainnet optimism, etc..

Related issues:
- [x] https://github.com/status-im/status-desktop/issues/7243
- [x] https://github.com/status-im/status-desktop/issues/7244
- [ ] https://github.com/status-im/status-desktop/issues/7534
- [ ] Use mainnet optimism (besides testnet optimism) depending on the config
- [x] #9728

**Comment by iurimatias** [comment]
pushed to 0.9.0 due to unexpected challenges with waku-js and the version used in the community portal app

**Comment by anastasiyaig** [comment]
@iurimatias there are some tasks left, should we move the epic to 0.10.0 and continue there?
