### ISSUE TITLE
[Epic]Sync + backup to / sync from Waku

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#8315]
We need to backup and sync almost all properties user may customize in the app. The full list of it will be added later when @John-44 prepares it. 

The list of items we need to support synchronize & backup to waku for is [here](https://docs.google.com/spreadsheets/d/1VyVIg5ZaVSlKWZRHSLzSMCMGJsbprkWUfEqCUJKma8w/edit#gid=507125679)

**List of issues we need sync + backup implementations for (status-go & desktop app):**
- [x] https://github.com/status-im/status-desktop/issues/8467
- [x] https://github.com/status-im/status-desktop/issues/8468
- [x] https://github.com/status-im/status-desktop/issues/8469
- [x] https://github.com/status-im/status-desktop/issues/10569 need to be implemented before #9654 
- [x] https://github.com/status-im/status-desktop/issues/10592 need to be implemented before #9654 
- [x] https://github.com/status-im/status-desktop/issues/8920
- [x] https://github.com/status-im/status-desktop/issues/9654
- [x] https://github.com/status-im/status-desktop/issues/11661

**List of issues we have a status-go implementation for, but missing a desktop app handling:**
- [x] https://github.com/status-im/status-desktop/issues/10389
- [x] https://github.com/status-im/status-desktop/issues/10390
- [ ] https://github.com/status-im/status-desktop/issues/10438

**Comment by jakubgs** [comment]
While testing out newest `go-waku` upgrade for `status-go`([#3213](https://github.com/status-im/status-go/pull/3213)) on `notify.prod` fleet I encountered this crash:
```
2023-02-24T09:17:28.637Z#011ERROR#011protocol/messenger_auto_message.go:52#011[auto message] failed to send message#011{"error": "Chat not found", "errorVerbose": "Chat not found\ngithub.com/status-im/status-go/protocol.(*Messenger).sendChatMessage\n\t/go/src/github.com/status-im/status-go/protocol/messenger.go:1991\ngithub.com/status-im/status-go/protocol.(*Messenger).SendChatMessage\n\t/go/src/github.com/status-im/status-go/protocol/messenger.go:1927\ngithub.com/status-im/status-go/protocol.(*Messenger).startAutoMessageLoop.func1\n\t/go/src/github.com/status-im/status-go/protocol/messenger_auto_message.go:50\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"}
github.com/status-im/status-go/protocol.(*Messenger).startAutoMessageLoop.func1
#011/go/src/github.com/status-im/status-go/protocol/messenger_auto_message.go:52
2023-02-24T09:17:28.637Z#011DEBUG#011protocol/messenger_backup.go:65#011backing up data
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x1b540e5]
goroutine 362 [running]:
github.com/status-im/status-go/protocol.(*Messenger).backupProfile(0xc001637680, {0x50ce06?, 0xc00516cd01?}, 0x18682b692bd)
#011/go/src/github.com/status-im/status-go/protocol/messenger_backup.go:314 +0xe5
github.com/status-im/status-go/protocol.(*Messenger).BackupData(0xc001637680, {0x2aaa300, 0xc003aa7a40})
#011/go/src/github.com/status-im/status-go/protocol/messenger_backup.go:88 +0xe5
github.com/status-im/status-go/protocol.(*Messenger).startBackupLoop.func1()
#011/go/src/github.com/status-im/status-go/protocol/messenger_backup.go:69 +0x225
created by github.com/status-im/status-go/protocol.(*Messenger).startBackupLoop
#011/go/src/github.com/status-im/status-go/protocol/messenger_backup.go:36 +0x8a
```
Most probably related to this code. Could you check it out?

**Comment by jakubgs** [comment]
This is how you can reproduce it: https://github.com/status-im/status-go/pull/3213#issuecomment-1442165917

**Comment by jakubgs** [comment]
I tried to make a config to reproduce this locally but instead I found another issue that blocks me:

* https://github.com/status-im/status-go/issues/3231

**Comment by saledjenic** [comment]
Ok, just update me once you find out which `config` causes a crash.

**Comment by jakubgs** [comment]
I tried testing a new image with fixes from Richard made in in https://github.com/status-im/status-go/pull/3229 with config:
```json
{
  "LogLevel": "INFO",
  "NodeKey": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "WakuConfig": { "Enabled": false },
  "WakuV2Config": { "Enabled": true, "EnableDiscV5": true, "Port": 30504 },
  "PushNotificationServerConfig": {
    "Enabled": true,
    "GorushURL": "https://gorush.infra.status.im"
  },
  "ClusterConfig": {
    "Enabled": true,
    "DiscV5BootstrapNodes": [
      "enr:-M-4QLOTEs_ZFxCb09FgIezZd5KeTru5CWWyEtMWMN-yUABrerWxckU-pMIh3yO8VjxHpgZ4jU2WSXuK3goW4uYb6c4BgmlkgnY0gmlwhI_G-a6KbXVsdGlhZGRyc7EALzYobm9kZS0wMS5kby1hbXMzLnN0YXR1cy5wcm9kLnN0YXR1c2ltLm5ldAYBu94DiXNlY3AyNTZrMaECoVyonsTGEQvVioM562Q1fjzTb_vKD152PPIdsV7sM6SDdGNwgnZfg3VkcIIjKIV3YWt1MgM"
    ]
  }
}
```
But now I'm getting:
```
2023-02-24T20:16:49.720Z	WARN	protocol/messenger.go:799	failed to fetch historic messages	{"error": "mailserver not available", "errorVerbose": "mailserver not available\ngithub.com/status-im/status-go/protocol.(*Messenger).performMailserverRequest\n\t/go/src/github.com/status-im/status-go/protocol/messenger_mailserver.go:117\ngithub.com/status-im/status-go/protocol.(*Messenger).RequestAllHistoricMessagesWithRetries\n\t/go/src/github.com/status-im/status-go/protocol/messenger_mailserver.go:297\ngithub.com/status-im/status-go/protocol.(*Messenger).handleConnectionChange.func1\n\t/go/src/github.com/status-im/status-go/protocol/messenger.go:797\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"}
github.com/status-im/status-go/protocol.(*Messenger).handleConnectionChange.func1
	/go/src/github.com/status-im/status-go/protocol/messenger.go:799
2023-02-24T20:16:49.720Z	DEBUG	pushnotificationclient/client.go:1516	nothing to do, quitting registration loop
2023-02-24T20:16:49.721Z	INFO	protocol/messenger_auto_message.go:35	[auto message] starting auto message loop
2023-02-24T20:16:49.721Z	DEBUG	pushnotificationclient/client.go:1461	no retriable notifications, quitting
2023-02-24T20:16:49.721Z	DEBUG	pushnotificationclient/client.go:1461	no retriable notifications, quitting
2023-02-24T20:16:49.721Z	DEBUG	pushnotificationclient/client.go:1516	nothing to do, quitting registration loop
2023-02-24T20:16:49.721Z	WARN	protocol/messenger_mailserver_cycle.go:65	not starting mailserver cycle
github.com/status-im/status-go/protocol.(*Messenger).StartMailserverCycle
	/go/src/github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:65
github.com/status-im/status-go/protocol.(*Messenger).Start
	/go/src/github.com/status-im/status-go/protocol/messenger.go:706
main.main
	/go/src/github.com/status-im/status-go/cmd/statusd/main.go:244
runtime.main
	/usr/local/go/src/runtime/proc.go:250
```
Seems like async stuff is messing up the logs. I'll look into it further on Monday.
