### ISSUE TITLE
Wallet: Polish SendModal

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#8484]
# Bug Report

## Description

After feedback from John and design, creating this task to address the points below: 

- [x] The intersection should not be a plus but a  T, actually there should be no intersection in between lines at all. https://github.com/status-im/status-desktop/issues/8515
- [x] The lines shown should start from the icon on the network card. https://github.com/status-im/status-desktop/issues/8515
- [x] The lines should be dashed https://github.com/status-im/status-desktop/issues/8515
- [x] Remove fees slow, optimal and fast only in simple view  https://github.com/status-im/status-desktop/issues/8516
- [x] * missing on send button - done under https://github.com/status-im/status-desktop/pull/8419
- [ ] Wrong Password not needed on send modal as the authentication modal handles that https://github.com/status-im/status-desktop/issues/8527
- [ ] sender Address in advanced view should be capitalised https://github.com/status-im/status-desktop/issues/8527
- [ ] While scrolling the gradient should show up on top of the content and not be added extra https://github.com/status-im/status-desktop/issues/8527
- [x]  The Networks names should be complete and not elide - **_The issue is that the networks names are longer than expected by design, elide needs some space as well to show the dots and hence we get cut of network names, if the names of the network were correct, it would appear correctly._**
- [ ] Also implement show unpreferred networks , and by default with no prefix paint is only preferred chain https://github.com/status-im/status-desktop/issues/8530

### Additional Information

- Status desktop version: master
- Operating System: Linux

**Comment by Khushboo-dev-cpp** [comment]
@John-44 the point about the network name not showing up completely in the advanced view, the issue really is that in the test mode the names are longer and otherwise on mainnet it looks alright like below. The first one elides cause the entire name of the network is Ethereum mainnet


![Image](https://user-images.githubusercontent.com/60327365/204873676-3d400405-e2df-4c7c-8ece-bf5630af171f.png)
