### ISSUE TITLE
[EPIC] Community Settings / Mint collectibles

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#8694]
**Description**

Related UI epic: https://github.com/status-im/status-desktop/issues/5981
figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A481546&t=6E3gZk9l72B1DqRy-0

**Tasks:**
- [x] [Welcome page](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=21764%3A486901&t=6E3gZk9l72B1DqRy-0) --> Only UI, no backend needed
    - https://github.com/status-im/status-desktop/issues/8732
- [x] [Create new collectible edit page](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A480877&t=6E3gZk9l72B1DqRy-0) --> UI and backend needed to get available networks and collectible object model to store data
   - https://github.com/status-im/status-desktop/issues/8733
   - **TODO: Backend related task**
- [x] [Create new collectible preview page](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A481005&t=6E3gZk9l72B1DqRy-0) --> UI and backend needed (collectible object model to store data)
   - https://github.com/status-im/status-desktop/issues/8734 
   - **TODO: Backend related task**
- [ ] [List of tokens/collectibles page](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A479136&t=6E3gZk9l72B1DqRy-0)  --> UI and backend needed to get list of existing minted tokens and collectibles and state of each
   - https://github.com/status-im/status-desktop/issues/8736 
   - **TODO: Backend related task**
- [x] [View collectible state page](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A479431&t=6E3gZk9l72B1DqRy-0) --> UI and backend needed to get holders and mint state
   - https://github.com/status-im/status-desktop/issues/8737
   - **TODO: Backend related task**
   
**Backend specific tasks:**
- [x] [Smart contract deployment in status-go](https://github.com/status-im/status-go/issues/3051) (cooperation with @gravityblast)
- [x] [Nim backend for minting functionality](https://github.com/status-im/status-desktop/issues/8921)
- [x] [Save deployed collectibles information in database.](https://github.com/status-im/status-desktop/issues/9233)
- [x] Expose smart contract functions for testing - not merged yet
- [ ] [Keep contract's metadata in waku](https://github.com/status-im/status-desktop/issues/9545)
- [ ] gas estimates for contract operations
- [ ] Keep contract's address and chainId in communityDescription ?
- [ ] token holders cache

**Pending clarifications:**
- [Sign transation page / flow](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=21786%3A488760&t=6E3gZk9l72B1DqRy-0) pending design / functionality
- [Airdrop, retail, remotely self-destruct, burn](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A479570&t=6E3gZk9l72B1DqRy-0) actions. Are they for MVP?
- How to integrate [signing (keycard + biometrics) flow](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=6575%3A77318&t=JlNZKPTxffDvrnit-0) into minting flow? Is it for MVP?
- What deployed smart contract info keep in database ?
- Who pays for deployment ? Owner/admin ?
