### ISSUE TITLE
[wallet] SendModal - lowering entropy in QML implementation

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#9443]
### Description

Send Modal has one of the most complex user workflows in the wallet module; hence the implementation is also complex and has grown organically. Even though it has already substantially improved, with this epic, we look into how to improve it even more

### Prototyping

Inconveniences

- Working with Send Modal requires starting the APP, waiting for tokens update, and having multiple accounts with different values to cover many cases, which is slow and error-prone.

Improvement brainstorming

- Add an abstraction layer based on the current MVC implementation and integrate it with Story-Book
  - This might require extensive work but can be done in steps using multiple facades and be finalized later on after MVP
  - I should improve a lot by refactoring and covering multiple use cases without depending on network requests and manual setup

### Layouting

Inconsistencies

- The main content is resized by [StackLayout](https://github.com/status-im/status-desktop/blob/46d4193bbdd4a993088a8bc91ebdc47944fe9105/ui/imports/shared/popups/SendModal.qml#L170) but can't see any usage for it (switching between multiple items)
- Some items have hardcoded sizes and don't adapt, e.g. [TokenListView](https://github.com/status-im/status-desktop/blob/46d4193bbdd4a993088a8bc91ebdc47944fe9105/ui/imports/shared/views/TokenListView.qml#L41)
- Layout hints follow the parent's size, e.g. [group1 ColumnLayout](https://github.com/status-im/status-desktop/blob/46d4193bbdd4a993088a8bc91ebdc47944fe9105/ui/imports/shared/popups/SendModal.qml#L177)
  - Defeats the purpose of size hints

Some first steps were started [with #9414 fix](https://github.com/status-im/status-desktop/pull/9414)

Improvement brainstorming

- [x] - Switch the main layout simple layout (ColumnLayout?) that takes size hints from the content (impicitWidth/implicitHeight)
- [x] - The underlying dialog implementation will adjust the size based on the layout's hints.
- [x]   - The dialog also has some size limitations, therefore have the main layout fill parent and follow these limits.
- [x]   - All items inside should offer size hints (preferred, min or max) and adapt to (layouts should work ok here)
- [x] - Scrollable content should be scrollable if the content doesn't fit the requirements.
- [x]   - e.g. `interactive: contentWidth > width`
- [x] - Follow contributing guidelines [Positioning and sizing(https://github.com/status-im/status-desktop/blob/46d4193bbdd4a993088a8bc91ebdc47944fe9105/ui/StatusQ/src/contributing.md#L44) and [Layouts](https://github.com/status-im/status-desktop/blob/46d4193bbdd4a993088a8bc91ebdc47944fe9105/ui/StatusQ/src/contributing.md#L85

Some more improvements that can also be moved out of this task and created as a separate task  are defined below , most of them involve moving logic from the UI to the BE (nim)

- [x] 1. When sending request the last request should be executed only #12243
- [x] 2. Cards should not be greyed out when loading is on going #12243
- [x] 3. Moving disabled and preferred chains ui state to him and make it more reliable?
- [x] 4. Calculating entered address and giving it colours can be done on him side
- [x] 5. The sendModal doesnt resize for simple networks #12243
- [ ] Let SendModal be completely demoed in storybook #12244 

- [x] #12140
- [ ] [Bug for 2nd notification for tx not shown](https://github.com/status-im/status-desktop/issues/12242)
- [x] #12206
- [x] #12222
- [x] #12149
- [x] Remove all chat send modal code, not needed and its annoying
- [ ] [can we add refresh buttons for assets/transactions?](https://github.com/status-im/status-desktop/issues/12240)
