### ISSUE TITLE
Community Settings / Airdrops EPIC

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#9795]
### Description

[[Design Flow]](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22721%3A498581&t=SvGXYDJSShCl5Ixk-1)

**UI TASKS**
- [ ] [Welcome page](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22602%3A495365&t=SvGXYDJSShCl5Ixk-1)
- [ ] [Extend holdings dropdown](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22628%3A493562&t=SvGXYDJSShCl5Ixk-0)
- [ ] [Extend StatusItemSelector Iteration 1](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22628%3A494998&t=SvGXYDJSShCl5Ixk-1) --> It should allow to add different item components, like here where we have the holding amount + network
- [ ] [Extend StatusItemSelector Iteration 2](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22628%3A495258&t=SvGXYDJSShCl5Ixk-1) --> It should allow to add eth addresses and eth members like in the design. Maybe it worths it to design a new component instead (Evaluate the possibilities)
- [ ] [Create eth members list dropdown](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22647%3A498410&t=SvGXYDJSShCl5Ixk-1)
- [ ] [Create airdrop page](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22602%3A495563&t=SvGXYDJSShCl5Ixk-1) --> Including the complete flow and warning cases

**Comment by iurimatias** [comment]
closing, just https://github.com/status-im/status-desktop/issues/9801 left and it's in progress
