### ISSUE TITLE
[Performance][EPIC] Move backend calls to threadpool

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#9816]
### Description
In this [task](https://github.com/status-im/status-desktop/issues/9739) we have identified the most expensive backend calls used at startup.

This is a list of expensive backend calls that can be easily moved to threadpool (based on this [benchmarking data](https://github.com/status-im/status-desktop/files/10922121/procBenchmark.csv)), prioritised based on gains over dev time:

- [x] callPrivateRPC - wakuext_getCommunitiesSettings - 10 sec ﻿
Used in a single place - https://github.com/status-im/status-desktop/blob/master/src/app_service/service/community/service.nim#L583
Issue https://github.com/status-im/status-desktop/issues/9825

- [x] callPrivateRPC - permissions_getDappPermissions - 5 sec
Used in a single place - https://github.com/status-im/status-desktop/blob/master/src/app_service/service/dapp_permissions/service.nim#L31
Easy refactoring
Issue: https://github.com/status-im/status-desktop/issues/9826

- [ ] ~~wallet_getEthereumChains - 4 sec
Used in a single place
https://github.com/status-im/status-desktop/blob/master/src/app_service/service/network/service.nim#L39~~

- [ ] wallet_checkRecentHistoryForChainIDs - 2 sec
Fire and forget, used in a single place
https://github.com/status-im/status-desktop/blob/master/src/app_service/service/wallet_account/service.nim#L298

- [x] callPrivateRPC - gif_setTenorAPIKey - 1.5 sec
Fire and forget. Used in a single place:
https://github.com/status-im/status-desktop/blob/master/src/app_service/service/gif/service.nim#L151
Issue: https://github.com/status-im/status-desktop/issues/9949

- [ ] callPrivateRPC - wakuext_activityCenterNotificationsCount - 2 sec with 39 calls
triggered by 
SIGNAL_ACTIVITY_CENTER_NOTIFICATIONS_COUNT_MAY_HAVE_CHANGED
or by UI

- [ ] wallet_getSavedAddresses - 1.8 sec
1 call at startup. Used in 2 places:
https://github.com/status-im/status-desktop/blob/master/src/app_service/service/saved_address/service.nim#L36
https://github.com/status-im/status-desktop/blob/master/src/app/modules/main/wallet_section/saved_addresses/module.nim#L33

- [x] callPrivateRPC - wakuext_pendingRequestsToJoinForCommunity - 1 sec
Used in a single place:
https://github.com/status-im/status-desktop/blob/master/src/app_service/service/community/service.nim#L579
Also part of https://github.com/status-im/status-desktop/issues/9825

**Comment by alexjba** [comment]
The benchmarking numbers are chaotic between runs for some calls. The range can get from a few ms to a few seconds. @richard-ramos could it be due to db locks or data locks in status-go? I'm using an account with full message history. When I use the same account without message history the numbers are much lower.

**Comment by richard-ramos** [comment]
Perhaps, we're using sqlcipher with concurrent access disabled as described in here. https://github.com/status-im/status-go/blob/develop/sqlite/sqlite.go#L84-L85 meaning that read/insert operations are done synchronously if i understand correctly.  In what operations do you see this slowness? maybe there's some index or query tuning that could be done to help improve performance?

**Comment by richard-ramos** [comment]
The SQL performed by those operations are not heavy at all (the total number of rows the tables used by these queries are very very few), which makes me think that it's another operation that's causing some db contention

getDappPermissions:
```
-- in a single transaction
SELECT id, name, address FROM dapps
SELECT dapp_id, permission from permissions
```

setTenorKey
```
UPDATE settings SET %s = ? WHERE synthetic_id = 'id'
```

getEthereumChains
```
SELECT chain_id, chain_name, rpc_url, fallback_url, block_explorer_url, icon_url, native_currency_name, native_currency_symbol, native_currency_decimals, is_test, layer, enabled, chain_color, short_name FROM networks
WHERE enabled = ?
```

**Comment by alexjba** [comment]
> The SQL performed by those operations are not heavy at all (the total number of rows the tables used by these queries are very very few), which makes me think that it's another operation that's causing some db contention
> 
> getDappPermissions:
> 
> ```
> -- in a single transaction
> SELECT id, name, address FROM dapps
> SELECT dapp_id, permission from permissions
> ```
> 
> setTenorKey
> 
> ```
> UPDATE settings SET %s = ? WHERE synthetic_id = 'id'
> ```
> 
> getEthereumChains
> 
> ```
> SELECT chain_id, chain_name, rpc_url, fallback_url, block_explorer_url, icon_url, native_currency_name, native_currency_symbol, native_currency_decimals, is_test, layer, enabled, chain_color, short_name FROM networks
> WHERE enabled = ?
> ```

@richard-ramos The benchmark numbers will stabilise if we call status-go from a single thread. This way I'm getting the expected performance for these queries. If I understand this correctly, we're running into db locks.

Do you think it would be worth considering a connection pool?
A possible implementation is described [here](https://turriate.com/articles/making-sqlite-faster-in-go).

**Comment by alexjba** [comment]
I've been running the app in a single thread to avoid the db locks and here are the results. There are multiple sheets from multiple runs to make sure the results are consistent.
[procBenchmark-oneThreadApp.xlsx](https://github.com/status-im/status-desktop/files/10958840/procBenchmark-oneThreadApp.xlsx)

**Comment by jrainville** [comment]
Cool. Yeah it seems like we have 3 main offenders. I'll create a task for `getChats` as it is the worst of them

**Comment by richard-ramos** [comment]
> The benchmark numbers will stabilise if we call status-go from a single thread. This way I'm getting the expected performance for these queries. If I understand this correctly, we're running into db locks.
> 
> Do you think it would be worth considering a connection pool? A possible implementation is described [here](https://turriate.com/articles/making-sqlite-faster-in-go).

Sounds like a good idea. We're already using WAL in status-go and creating prepared statements when the services are initiated should be somewhat easy to implement. No idea if we have tried before to use a connection pool and shared cache. We also have to verify if the sqlcipher driver we use supports these features. cc-ing: @cammellos and @rasom for their insights in case these approaches have been tried before

**Comment by cammellos** [comment]
If I read well, getChats takes 64 seconds?
We don't use that particular method in status-mobile, but it still seems too high, have we tried to hit directly status-go to make sure there's no issue somewhere else?
(On mobile as far as I can see, we don't have these numbers, and run in much lowered power devices)

**Comment by cammellos** [comment]
Oh, now that I look at the code, I see that it calls pinned message by chat id for each chat, and it looks like the query has been made quite more complex after introducing discord messages, and you mention you tested on a database with quite a few messages, it seems this could be the issue

**Comment by jrainville** [comment]
> what do you need it for exactly?

We use it currently to generate all the sections and get all the initial data for all chats. It made life easier, as it got everything needed and considered all chats as similar. 
We did it as a simplification, since we used to have lots of conditions on the type of chat and there were different apis called based on that, so we tried to consolidate everything in one call.

So we are here now. Turns out it's not that great when we have such a big DB in SQLite. It takes way too much time.

So we're planning on either split `getChats` to use it in a smarter way, or we can look at how you do it on mobile. I think our initial way, before introducing `getChats`, was based on mobile, but you guys might have improved it as well since then.

**Comment by jrainville** [comment]
> most likely the issue is with the pinned messages query

Yeah, it seems like this call is pretty slow, so doing it on every chat at the app start sounds like a bad idea nonetheless

**Comment by alexjba** [comment]
@jrainville Can we close this? Not sure it's relevant any more with all the performance improvements we've had.

**Comment by jrainville** [comment]
Agreed. Closing since the main culprits have been fixed and the remaining ones were mainly just victims of the DB locks, which have been fixed
