### ISSUE TITLE
[Epic] Contact Requests

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#9896]
### Description

Fixing & improving contact requests

- [x] https://github.com/status-im/status-desktop/issues/9788
- [x] status-im/status-desktop#9898
- [x] status-im/status-desktop#9897
- [x] status-im/status-desktop#9901
- [x] status-im/status-desktop#9939
- [ ] status-im/feature-specs#95
- [x] status-im/status-desktop#10127
- [x] https://github.com/status-im/status-go/issues/3326
- [x] status-im/status-desktop#10158
- [x] https://github.com/status-im/status-desktop/issues/9935
- [x] status-im/status-desktop#10268
- [ ] status-im/status-desktop#10395
- [ ] status-im/status-desktop#10400
- [ ] #10441

**Comment by iurimatias** [comment]
closing as all issues are now created and can be found under the "Mutual contacts" Category
